"""init table

Revision ID: 761fde38c62c
Revises: 
Create Date: 2025-08-13 16:33:43.709431

"""
from typing import Sequence, Union

from alembic import op
import models as models
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '761fde38c62c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_key_info',
    sa.Column('id', sa.Integer(), nullable=False, comment='api key id'),
    sa.Column('name', sa.String(), nullable=True, comment='api key name'),
    sa.Column('api_key', sa.String(), nullable=True, comment='api key'),
    sa.Column('hash_key', sa.String(), nullable=True, comment='api key hash'),
    sa.Column('salt', sa.String(), nullable=True, comment='api key salt'),
    sa.Column('description', sa.String(), nullable=True, comment='api key description'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='api key create time'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='api key update time'),
    sa.Column('deleted', sa.Integer(), nullable=True, comment='api key delete flag'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_key'),
    sa.UniqueConstraint('hash_key')
    )
    op.create_index(op.f('ix_api_key_info_id'), 'api_key_info', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_api_key_info_id'), table_name='api_key_info')
    op.drop_table('api_key_info')
    # ### end Alembic commands ###
