"""6

Revision ID: 6afa9b8c0109
Revises: e58227d6ee71
Create Date: 2025-09-01 22:27:29.918359

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '6afa9b8c0109'
down_revision: Union[str, None] = 'e58227d6ee71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mcp_user',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('type', sa.String(length=128), nullable=False),
    sa.Column('is_is_anonymous', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('external_user_id', sa.String(length=256), nullable=True),
    sa.Column('session_id', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='create time'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='update time'),
    sa.Column('deleted', sa.Integer(), nullable=True, comment='delete flag'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mcp_user_external_user_id'), 'mcp_user', ['external_user_id'], unique=False)
    op.create_index(op.f('ix_mcp_user_name'), 'mcp_user', ['name'], unique=False)
    op.create_index(op.f('ix_mcp_user_session_id'), 'mcp_user', ['session_id'], unique=False)
    op.create_index(op.f('ix_mcp_user_type'), 'mcp_user', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mcp_user_type'), table_name='mcp_user')
    op.drop_index(op.f('ix_mcp_user_session_id'), table_name='mcp_user')
    op.drop_index(op.f('ix_mcp_user_name'), table_name='mcp_user')
    op.drop_index(op.f('ix_mcp_user_external_user_id'), table_name='mcp_user')
    op.drop_table('mcp_user')
    # ### end Alembic commands ###
