"""10

Revision ID: f8dcd1a71fb2
Revises: 0b7295d70fc6
Create Date: 2025-09-11 19:24:36.099695

"""
from typing import Sequence, Union

from alembic import op
import models as models
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f8dcd1a71fb2'
down_revision: Union[str, None] = '0b7295d70fc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_resources',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False, comment='id'),
    sa.Column('access_url', sa.String(), server_default=sa.text("''"), nullable=True, comment='access_url'),
    sa.Column('file_name', sa.String(), server_default=sa.text("''"), nullable=True, comment='file name'),
    sa.Column('file_abs_path', sa.String(), server_default=sa.text("''"), nullable=True, comment='file absolute path'),
    sa.Column('file_type', sa.String(), server_default=sa.text("''"), nullable=True, comment='file type'),
    sa.Column('file_size', sa.Integer(), nullable=True, comment='file size'),
    sa.Column('file_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'"), nullable=True, comment='file metadata'),
    sa.Column('file_hash', sa.String(), server_default=sa.text("''"), nullable=True, comment='file hash'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='create time'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='update time'),
    sa.Column('deleted', sa.Integer(), nullable=True, comment='delete flag'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_resources_access_url'), 'file_resources', ['access_url'], unique=False)
    op.create_index(op.f('ix_file_resources_file_abs_path'), 'file_resources', ['file_abs_path'], unique=False)
    op.create_index(op.f('ix_file_resources_file_hash'), 'file_resources', ['file_hash'], unique=False)
    op.create_index(op.f('ix_file_resources_file_name'), 'file_resources', ['file_name'], unique=False)
    op.create_table('message_token_usage',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False, comment='id'),
    sa.Column('message_id', sa.String(), nullable=False, comment='message id'),
    sa.Column('model_name', sa.String(), nullable=False, comment='model name'),
    sa.Column('provider_name', sa.String(), nullable=False, comment='provider name'),
    sa.Column('prompt_tokens', sa.Integer(), server_default=sa.text("'0'"), nullable=False, comment='number of prompt tokens'),
    sa.Column('completion_tokens', sa.Integer(), server_default=sa.text("'0'"), nullable=False, comment='number of completion tokens'),
    sa.Column('total_tokens', sa.Integer(), server_default=sa.text("'0'"), nullable=False, comment='total number of tokens'),
    sa.Column('prompt_unit_price', sa.DECIMAL(), server_default=sa.text("'0.0000000'"), nullable=False, comment='prompt unit price'),
    sa.Column('prompt_price', sa.DECIMAL(), server_default=sa.text("'0.0000000'"), nullable=False, comment='prompt price'),
    sa.Column('completion_unit_price', sa.DECIMAL(), server_default=sa.text("'0.0000000'"), nullable=False, comment='completion unit price'),
    sa.Column('completion_price', sa.DECIMAL(), server_default=sa.text("'0.0000000'"), nullable=False, comment='completion price'),
    sa.Column('total_price', sa.DECIMAL(), server_default=sa.text("'0.0000000'"), nullable=False, comment='total price'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='create time'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='update time'),
    sa.Column('deleted', sa.Integer(), nullable=True, comment='delete flag'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_token_usage_message_id'), 'message_token_usage', ['message_id'], unique=False)
    op.create_index(op.f('ix_message_token_usage_model_name'), 'message_token_usage', ['model_name'], unique=False)
    op.create_index(op.f('ix_message_token_usage_provider_name'), 'message_token_usage', ['provider_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_token_usage_provider_name'), table_name='message_token_usage')
    op.drop_index(op.f('ix_message_token_usage_model_name'), table_name='message_token_usage')
    op.drop_index(op.f('ix_message_token_usage_message_id'), table_name='message_token_usage')
    op.drop_table('message_token_usage')
    op.drop_index(op.f('ix_file_resources_file_name'), table_name='file_resources')
    op.drop_index(op.f('ix_file_resources_file_hash'), table_name='file_resources')
    op.drop_index(op.f('ix_file_resources_file_abs_path'), table_name='file_resources')
    op.drop_index(op.f('ix_file_resources_access_url'), table_name='file_resources')
    op.drop_table('file_resources')
    # ### end Alembic commands ###
