"""2

Revision ID: 864e0d197726
Revises: a139f4ce6157
Create Date: 2025-08-23 10:48:20.785313

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '864e0d197726'
down_revision: Union[str, None] = 'a139f4ce6157'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_key_info', sa.Column('source', sa.String(), nullable=True, comment='api key source'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_key_info', 'source')
    # ### end Alembic commands ###
