"""3

Revision ID: edf72bdc03e1
Revises: 864e0d197726
Create Date: 2025-08-23 16:32:00.079579

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'edf72bdc03e1'
down_revision: Union[str, None] = '864e0d197726'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tool_call_result',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('message_id', sa.String(), nullable=True, comment='message id'),
    sa.Column('tool_call_id', sa.String(), nullable=True, comment='tool call id'),
    sa.Column('tool_call', sa.JSON(), nullable=True, comment='tool calls'),
    sa.Column('result', sa.JSON(), nullable=True, comment='tool call result'),
    sa.Column('state', sa.String(), nullable=False, comment='tool call state'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='api key create time'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='api key update time'),
    sa.Column('deleted', sa.Integer(), nullable=True, comment='api key delete flag'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tool_call_result_message_id'), 'tool_call_result', ['message_id'], unique=False)
    op.create_index(op.f('ix_tool_call_result_tool_call_id'), 'tool_call_result', ['tool_call_id'], unique=False)
    op.create_table('tool_info',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('name', sa.String(), nullable=True, comment='tool name'),
    sa.Column('description', sa.String(), nullable=True, comment='tool description'),
    sa.Column('parameters', sa.JSON(), nullable=True, comment='tool parameters schema'),
    sa.Column('configs', sa.JSON(), nullable=True, comment='tool configurations'),
    sa.Column('icon', sa.String(), nullable=True, comment='tool icon'),
    sa.Column('provider', sa.String(), nullable=True, comment='tool provider type'),
    sa.Column('type', sa.String(), nullable=True, comment='tool type'),
    sa.Column('credentials', sa.String(), nullable=True, comment='tool credentials'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='tool create time'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='tool update time'),
    sa.Column('deleted', sa.Integer(), nullable=True, comment='tool delete flag'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table_comment(
        'api_key_info',
        'api key table',
        existing_comment=None,
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table_comment(
        'api_key_info',
        existing_comment='api key table',
        schema=None
    )
    op.drop_table('tool_info')
    op.drop_index(op.f('ix_tool_call_result_tool_call_id'), table_name='tool_call_result')
    op.drop_index(op.f('ix_tool_call_result_message_id'), table_name='tool_call_result')
    op.drop_table('tool_call_result')
    # ### end Alembic commands ###
