"""8

Revision ID: 6ee3aa0992f3
Revises: 180b10953bab
Create Date: 2025-09-11 02:07:04.232926

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '6ee3aa0992f3'
down_revision: Union[str, None] = '180b10953bab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('browser_history',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False, comment='browser history id'),
    sa.Column('url', sa.String(), nullable=True, comment='browsed url'),
    sa.Column('ua', sa.String(), nullable=True, comment='user agent'),
    sa.Column('title', sa.String(), nullable=True, comment='page title'),
    sa.Column('crawl_task_id', sa.String(), nullable=True, comment='crawl task id'),
    sa.Column('crawl_content', sa.TEXT(), nullable=True, comment='crawl content'),
    sa.Column('crawl_type', sa.String(), nullable=True, comment='crawl type'),
    sa.Column('crawl_media', sa.TEXT(), nullable=True, comment='crawl media json'),
    sa.Column('crawl_metadata', sa.String(), nullable=True, comment='additional metadata json'),
    sa.Column('crawl_screenshot', sa.String(), nullable=True, comment='crawl screenshot url'),
    sa.Column('crawl_time', sa.DateTime(), nullable=True, comment='crawl time'),
    sa.Column('crawl_status', sa.BOOLEAN(), nullable=True, comment='crawl status'),
    sa.Column('visit_time', sa.DateTime(), nullable=True, comment='visit time'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='history create time'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='history update time'),
    sa.Column('deleted', sa.Integer(), nullable=True, comment='history delete flag'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_browser_history_url'), 'browser_history', ['url'], unique=False)
    op.create_index('ix_crawl_content', 'browser_history', [sa.literal_column("to_tsvector('jieba_cfg', crawl_content)")], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_crawl_content', table_name='browser_history', postgresql_using='gin')
    op.drop_index(op.f('ix_browser_history_url'), table_name='browser_history')
    op.drop_table('browser_history')
    # ### end Alembic commands ###
