"""17

Revision ID: af820b9571d0
Revises: 63ec27c9d9f2
Create Date: 2025-09-18 19:44:33.901970

"""
from typing import Sequence, Union

from alembic import op
import models as models
import sqlalchemy as sa
import pgvecto_rs.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'af820b9571d0'
down_revision: Union[str, None] = '63ec27c9d9f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('knowledge_embeddings', 'vector',
               existing_type=pgvecto_rs.sqlalchemy.vector.VECTOR(2560),
               nullable=True,
               existing_comment='vector')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('knowledge_embeddings', 'vector',
               existing_type=pgvecto_rs.sqlalchemy.vector.VECTOR(2560),
               nullable=False,
               existing_comment='vector')
    # ### end Alembic commands ###
