"""16

Revision ID: 63ec27c9d9f2
Revises: bf9e62234706
Create Date: 2025-09-18 16:26:45.087503

"""
from typing import Sequence, Union

from alembic import op
import models as models
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63ec27c9d9f2'
down_revision: Union[str, None] = 'bf9e62234706'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('knowledge_document', 'rag_status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_comment='rag status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('knowledge_document', 'rag_status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_comment='rag status')
    # ### end Alembic commands ###
