"""24

Revision ID: 39ba93f58818
Revises: e89b3f534609
Create Date: 2025-10-09 14:20:13.694126

"""
from typing import Sequence, Union

from alembic import op
import models as models
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39ba93f58818'
down_revision: Union[str, None] = 'e89b3f534609'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent', sa.Column('enabled_memory', sa.Integer(), server_default=sa.text('0'), nullable=True, comment='Enable memory'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent', 'enabled_memory')
    # ### end Alembic commands ###
