"""19

Revision ID: b64d150cffd9
Revises: 230b4b6e2c7a
Create Date: 2025-09-21 16:18:48.906668

"""
from typing import Sequence, Union

from alembic import op
import models as models
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b64d150cffd9'
down_revision: Union[str, None] = '230b4b6e2c7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent',
    sa.Column('id', sa.Integer(), nullable=False, comment='id'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Agent name'),
    sa.Column('description', sa.String(length=255), server_default=sa.text("''"), nullable=True, comment='Agent description'),
    sa.Column('model_id', sa.String(length=255), nullable=False, comment='Model ID'),
    sa.Column('prompt_template', sa.TEXT(), server_default=sa.text("''"), nullable=False, comment='Prompt template'),
    sa.Column('tools', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'"), nullable=True, comment='Tools'),
    sa.Column('agent_parameters', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'"), nullable=True, comment='Agent parameters'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='create time'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='update time'),
    sa.Column('deleted', sa.Integer(), nullable=True, comment='delete flag'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_id'), 'agent', ['id'], unique=False)
    op.create_index(op.f('ix_agent_name'), 'agent', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_name'), table_name='agent')
    op.drop_index(op.f('ix_agent_id'), table_name='agent')
    op.drop_table('agent')
    # ### end Alembic commands ###
