"""21

Revision ID: 23fe0c09773c
Revises: 3d93c7aafc39
Create Date: 2025-09-22 16:15:58.802803

"""
from typing import Sequence, Union

from alembic import op
import models as models
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23fe0c09773c'
down_revision: Union[str, None] = '3d93c7aafc39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agent_session', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               existing_comment='Session name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agent_session', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               existing_comment='Session name')
    # ### end Alembic commands ###
