"""15

Revision ID: bf9e62234706
Revises: aa850c2132d8
Create Date: 2025-09-18 16:25:40.350619

"""
from typing import Sequence, Union

from alembic import op
import models as models
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf9e62234706'
down_revision: Union[str, None] = 'aa850c2132d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('knowledge_document', 'error_message',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               existing_comment='error message',
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('knowledge_keywords', 'keyword',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               existing_comment='keyword')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('knowledge_keywords', 'keyword',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               existing_comment='keyword')
    op.alter_column('knowledge_document', 'error_message',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               existing_comment='error message',
               existing_server_default=sa.text("''::character varying"))
    # ### end Alembic commands ###
