"""1

Revision ID: a139f4ce6157
Revises: 
Create Date: 2025-08-22 02:22:34.543343

"""
from typing import Sequence, Union

from alembic import op
import models as models
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a139f4ce6157'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_key_info',
    sa.Column('id', sa.Integer(), nullable=False, comment='api key id'),
    sa.Column('name', sa.String(), nullable=True, comment='api key name'),
    sa.Column('api_key', sa.String(), nullable=True, comment='api key'),
    sa.Column('hash_key', sa.String(), nullable=True, comment='api key hash'),
    sa.Column('salt', sa.String(), nullable=True, comment='api key salt'),
    sa.Column('description', sa.String(), nullable=True, comment='api key description'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='api key create time'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='api key update time'),
    sa.Column('deleted', sa.Integer(), nullable=True, comment='api key delete flag'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_key'),
    sa.UniqueConstraint('hash_key')
    )
    op.create_index(op.f('ix_api_key_info_id'), 'api_key_info', ['id'], unique=False)
    op.create_table('conversation_message',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('message_id', sa.String(), nullable=False, comment='conversation id'),
    sa.Column('model_name', sa.String(), nullable=False, comment='model name used for this message'),
    sa.Column('provider_name', sa.String(), nullable=False, comment='provider name used for this message'),
    sa.Column('system_prompt', sa.Text(), nullable=True, comment='system prompt for the conversation'),
    sa.Column('content', sa.Text(), nullable=False, comment='message content'),
    sa.Column('role', sa.String(), nullable=False, comment='message role (user/assistant)'),
    sa.Column('usage', sa.JSON(), nullable=True, comment='message usage information'),
    sa.Column('state', sa.String(), nullable=False, comment='message state'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='api key create time'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='api key update time'),
    sa.Column('deleted', sa.Integer(), nullable=True, comment='api key delete flag'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_content', 'conversation_message', [sa.literal_column("to_tsvector('jieba_cfg', content)")], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_conversation_message_model_name'), 'conversation_message', ['model_name'], unique=False)
    op.create_index(op.f('ix_conversation_message_provider_name'), 'conversation_message', ['provider_name'], unique=False)
    op.create_table('provider',
    sa.Column('id', sa.Integer(), nullable=False, comment='Provider ID'),
    sa.Column('name', sa.String(), nullable=False, comment='Provider Name'),
    sa.Column('support_model_type', sa.JSON(), nullable=False, comment='Supported Model'),
    sa.Column('provider_type', sa.String(), nullable=False, comment='Provider Type'),
    sa.Column('provider_config', sa.JSON(), nullable=False, comment='Provider Config'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='api key create time'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='api key update time'),
    sa.Column('deleted', sa.Integer(), nullable=True, comment='api key delete flag'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_provider_id'), 'provider', ['id'], unique=False)
    op.create_table('model',
    sa.Column('id', sa.Integer(), nullable=False, comment='Model ID'),
    sa.Column('name', sa.String(), nullable=True, comment='Model Name'),
    sa.Column('type', sa.String(), nullable=True, comment='Model Type'),
    sa.Column('provider_name', sa.String(), nullable=True, comment='Model Provider'),
    sa.Column('provider_id', sa.Integer(), nullable=True, comment='Model Provider ID'),
    sa.Column('max_tokens', sa.Integer(), nullable=True, comment='Max Tokens'),
    sa.Column('input_price', sa.DECIMAL(precision=10, scale=2), nullable=True, comment='Input Price'),
    sa.Column('output_price', sa.DECIMAL(precision=10, scale=2), nullable=True, comment='Output Price'),
    sa.Column('currency', sa.String(), nullable=True, comment='Model currency'),
    sa.Column('feature', sa.JSON(), nullable=True, comment='Model Feature'),
    sa.Column('model_params', sa.JSON(), nullable=True, comment='Model Params'),
    sa.Column('description', sa.String(), nullable=True, comment='Model Description'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='api key create time'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='api key update time'),
    sa.Column('deleted', sa.Integer(), nullable=True, comment='api key delete flag'),
    sa.ForeignKeyConstraint(['provider_id'], ['provider.id'], name='fk_model_provider_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'provider_name', name='uq_model_name_provider')
    )
    op.create_index(op.f('ix_model_id'), 'model', ['id'], unique=False)
    op.create_index(op.f('ix_model_max_tokens'), 'model', ['max_tokens'], unique=False)
    op.create_index(op.f('ix_model_name'), 'model', ['name'], unique=False)
    op.create_index(op.f('ix_model_provider_id'), 'model', ['provider_id'], unique=False)
    op.create_index(op.f('ix_model_provider_name'), 'model', ['provider_name'], unique=False)
    op.create_index(op.f('ix_model_type'), 'model', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_model_type'), table_name='model')
    op.drop_index(op.f('ix_model_provider_name'), table_name='model')
    op.drop_index(op.f('ix_model_provider_id'), table_name='model')
    op.drop_index(op.f('ix_model_name'), table_name='model')
    op.drop_index(op.f('ix_model_max_tokens'), table_name='model')
    op.drop_index(op.f('ix_model_id'), table_name='model')
    op.drop_table('model')
    op.drop_index(op.f('ix_provider_id'), table_name='provider')
    op.drop_table('provider')
    op.drop_index(op.f('ix_conversation_message_provider_name'), table_name='conversation_message')
    op.drop_index(op.f('ix_conversation_message_model_name'), table_name='conversation_message')
    op.drop_index('ix_content', table_name='conversation_message', postgresql_using='gin')
    op.drop_table('conversation_message')
    op.drop_index(op.f('ix_api_key_info_id'), table_name='api_key_info')
    op.drop_table('api_key_info')
    # ### end Alembic commands ###
