"""26

Revision ID: 98da7bd5184c
Revises: 7c91ec671d79
Create Date: 2025-12-10 00:20:22.033403

"""
from typing import Sequence, Union

from alembic import op
import models as models
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98da7bd5184c'
down_revision: Union[str, None] = '7c91ec671d79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge_document', sa.Column('push_count', sa.Integer(), server_default=sa.text('0'), nullable=True, comment='push count'))
    op.add_column('knowledge_document', sa.Column('rag_count', sa.Integer(), server_default=sa.text('0'), nullable=True, comment='rag count'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('knowledge_document', 'rag_count')
    op.drop_column('knowledge_document', 'push_count')
    # ### end Alembic commands ###
