"""9

Revision ID: 0b7295d70fc6
Revises: 6ee3aa0992f3
Create Date: 2025-09-11 12:25:47.462625

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0b7295d70fc6'
down_revision: Union[str, None] = '6ee3aa0992f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('browser_history', 'crawl_media',
                    existing_type=sa.TEXT(),
                    type_=postgresql.JSONB(astext_type=sa.Text()),
                    existing_comment='crawl media json',
                    postgresql_using="crawl_media::jsonb",
                    existing_nullable=True)
    op.alter_column('browser_history', 'crawl_metadata',
                    existing_type=sa.VARCHAR(),
                    type_=postgresql.JSONB(astext_type=sa.Text()),
                    existing_comment='additional metadata json',
                    postgresql_using="crawl_metadata::jsonb",
                    existing_nullable=True)
    op.create_index('crawl_metadata', 'browser_history', [sa.literal_column('crawl_metadata')], unique=False,
                    postgresql_using='gin')
    op.drop_column('browser_history', 'crawl_task_id')
    op.drop_column('browser_history', 'crawl_status')
    op.drop_column('browser_history', 'title')
    op.create_index('ix_system_prompt', 'conversation_message',
                    [sa.literal_column("to_tsvector('jieba_cfg', system_prompt)")], unique=False,
                    postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_system_prompt', table_name='conversation_message', postgresql_using='gin')
    op.add_column('browser_history',
                  sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True, comment='page title'))
    op.add_column('browser_history',
                  sa.Column('crawl_status', sa.BOOLEAN(), autoincrement=False, nullable=True, comment='crawl status'))
    op.add_column('browser_history',
                  sa.Column('crawl_task_id', sa.VARCHAR(), autoincrement=False, nullable=True, comment='crawl task id'))
    op.drop_index('crawl_metadata', table_name='browser_history', postgresql_using='gin')
    op.alter_column('browser_history', 'crawl_metadata',
                    existing_type=postgresql.JSONB(astext_type=sa.Text()),
                    type_=sa.VARCHAR(),
                    existing_comment='additional metadata json',
                    existing_nullable=True)
    op.alter_column('browser_history', 'crawl_media',
                    existing_type=postgresql.JSONB(astext_type=sa.Text()),
                    type_=sa.TEXT(),
                    existing_comment='crawl media json',
                    existing_nullable=True)
    # ### end Alembic commands ###
