"""23

Revision ID: e89b3f534609
Revises: 179ee926269c
Create Date: 2025-09-27 11:13:46.825231

"""
from typing import Sequence, Union

from alembic import op
import models as models
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e89b3f534609'
down_revision: Union[str, None] = '179ee926269c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tool_info', sa.Column('mcp_server_code', sa.String(), server_default=sa.text("''"), nullable=True, comment='mcp server code'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tool_info', 'mcp_server_code')
    # ### end Alembic commands ###
