"""20

Revision ID: 3d93c7aafc39
Revises: b64d150cffd9
Create Date: 2025-09-22 16:07:57.993416

"""
from typing import Sequence, Union

from alembic import op
import models as models
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d93c7aafc39'
down_revision: Union[str, None] = 'b64d150cffd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_session',
    sa.Column('id', sa.Integer(), nullable=False, comment='id'),
    sa.Column('agent_id', sa.Integer(), nullable=True, comment='Agent ID'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Session name'),
    sa.Column('description', sa.String(length=255), server_default=sa.text("''"), nullable=True, comment='Session description'),
    sa.Column('status', sa.String(length=64), nullable=False, comment='Session status'),
    sa.Column('context', sa.TEXT(), server_default=sa.text("''"), nullable=True, comment='Session context'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='create time'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='update time'),
    sa.Column('deleted', sa.Integer(), nullable=True, comment='delete flag'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_session_agent_id'), 'agent_session', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_session_id'), 'agent_session', ['id'], unique=False)
    op.create_index(op.f('ix_agent_session_name'), 'agent_session', ['name'], unique=False)
    op.create_index(op.f('ix_agent_session_status'), 'agent_session', ['status'], unique=False)
    op.add_column('conversation_message', sa.Column('agent_id', sa.Integer(), nullable=True, comment='agent id'))
    op.add_column('conversation_message', sa.Column('agent_session_id', sa.Integer(), nullable=True, comment='agent session id'))
    op.create_index(op.f('ix_conversation_message_agent_id'), 'conversation_message', ['agent_id'], unique=False)
    op.create_index(op.f('ix_conversation_message_agent_session_id'), 'conversation_message', ['agent_session_id'], unique=False)
    op.add_column('message_token_usage', sa.Column('agent_id', sa.Integer(), nullable=True, comment='agent id'))
    op.add_column('message_token_usage', sa.Column('agent_session_id', sa.Integer(), nullable=True, comment='agent session id'))
    op.create_index(op.f('ix_message_token_usage_agent_id'), 'message_token_usage', ['agent_id'], unique=False)
    op.create_index(op.f('ix_message_token_usage_agent_session_id'), 'message_token_usage', ['agent_session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_token_usage_agent_session_id'), table_name='message_token_usage')
    op.drop_index(op.f('ix_message_token_usage_agent_id'), table_name='message_token_usage')
    op.drop_column('message_token_usage', 'agent_session_id')
    op.drop_column('message_token_usage', 'agent_id')
    op.drop_index(op.f('ix_conversation_message_agent_session_id'), table_name='conversation_message')
    op.drop_index(op.f('ix_conversation_message_agent_id'), table_name='conversation_message')
    op.drop_column('conversation_message', 'agent_session_id')
    op.drop_column('conversation_message', 'agent_id')
    op.drop_index(op.f('ix_agent_session_status'), table_name='agent_session')
    op.drop_index(op.f('ix_agent_session_name'), table_name='agent_session')
    op.drop_index(op.f('ix_agent_session_id'), table_name='agent_session')
    op.drop_index(op.f('ix_agent_session_agent_id'), table_name='agent_session')
    op.drop_table('agent_session')
    # ### end Alembic commands ###
