"""12

Revision ID: 158bdacfae63
Revises: 30ec504772fc
Create Date: 2025-09-17 17:32:28.628626

"""
from typing import Sequence, Union

from alembic import op
import models as models
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '158bdacfae63'
down_revision: Union[str, None] = '30ec504772fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('model', 'input_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.DECIMAL(precision=10, scale=7),
               existing_comment='Input Price',
               existing_nullable=True)
    op.alter_column('model', 'output_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.DECIMAL(precision=10, scale=7),
               existing_comment='Output Price',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('model', 'output_price',
               existing_type=sa.DECIMAL(precision=10, scale=7),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_comment='Output Price',
               existing_nullable=True)
    op.alter_column('model', 'input_price',
               existing_type=sa.DECIMAL(precision=10, scale=7),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_comment='Input Price',
               existing_nullable=True)
    # ### end Alembic commands ###
