"""18

Revision ID: 230b4b6e2c7a
Revises: af820b9571d0
Create Date: 2025-09-19 01:54:50.287974

"""
from typing import Sequence, Union

import pgvecto_rs.sqlalchemy
from alembic import op
import models as models
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '230b4b6e2c7a'
down_revision: Union[str, None] = 'af820b9571d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('knowledge_embeddings', 'vector',
               existing_type=pgvecto_rs.sqlalchemy.vector.VECTOR(4096),
               comment='embedding vector',
               existing_comment='vector',
               existing_nullable=True)
    op.drop_column('knowledge_embeddings', 'provider_name')
    op.drop_column('knowledge_embeddings', 'model_name')
    op.drop_index('idx_knowledge_embeddings_vector', table_name='knowledge_embeddings')
    op.create_index('idx_knowledge_embeddings_vector', 'knowledge_embeddings', ['vector'], unique=False,
                    postgresql_using='vectors', postgresql_with={
            'options': '$$optimizing.optimizing_threads = 30\n                                segment.max_growing_segment_size = 2000\n                                segment.max_sealed_segment_size = 30000000\n                                [indexing.hnsw]\n                                m=30\n                                ef_construction=500$$'},
                    postgresql_ops={'vector': 'vector_l2_ops'})

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge_embeddings', sa.Column('model_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True, comment='embedding model name'))
    op.add_column('knowledge_embeddings', sa.Column('provider_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True, comment='embedding provider name'))
    op.alter_column('knowledge_embeddings', 'vector',
               existing_type=pgvecto_rs.sqlalchemy.vector.VECTOR(4096),
               comment='vector',
               existing_comment='embedding vector',
               existing_nullable=True)
    # ### end Alembic commands ###
