"""22

Revision ID: 179ee926269c
Revises: 23fe0c09773c
Create Date: 2025-09-26 13:38:42.546984

"""
from typing import Sequence, Union

from alembic import op
import models as models
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '179ee926269c'
down_revision: Union[str, None] = '23fe0c09773c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation_message', sa.Column('model_parameters', sa.Text(), server_default=sa.text("'{}'"), nullable=True, comment='model parameters in json format'))
    op.add_column('knowledge_document', sa.Column('message_id', sa.String(), nullable=True, comment='message id'))
    op.alter_column('knowledge_document', 'file_id',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_comment='file id')
    op.create_index(op.f('ix_knowledge_document_message_id'), 'knowledge_document', ['message_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_knowledge_document_message_id'), table_name='knowledge_document')
    op.alter_column('knowledge_document', 'file_id',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_comment='file id')
    op.drop_column('knowledge_document', 'message_id')
    op.drop_column('conversation_message', 'model_parameters')
    # ### end Alembic commands ###
