"""7

Revision ID: 180b10953bab
Revises: 6afa9b8c0109
Create Date: 2025-09-01 22:30:02.666313

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '180b10953bab'
down_revision: Union[str, None] = '6afa9b8c0109'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mcp_user', 'external_user_id',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.UUID(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mcp_user', 'external_user_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=256),
               existing_nullable=True)
    # ### end Alembic commands ###
