"""27

Revision ID: 6fc8c551fb9a
Revises: 98da7bd5184c
Create Date: 2025-12-25 21:02:49.979777

"""
from typing import Sequence, Union

from alembic import op
import models as models
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6fc8c551fb9a'
down_revision: Union[str, None] = '98da7bd5184c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qa_memory_record',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False, comment='Project or workspace identifier'),
    sa.Column('knowledge_base_id', sa.UUID(), nullable=False),
    sa.Column('rag_type', sa.String(length=32), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.Float(), server_default=sa.text('0.5'), nullable=False),
    sa.Column('trust_score', sa.Float(), server_default=sa.text('0.5'), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('strong_signal_count', sa.Integer(), nullable=False),
    sa.Column('ttl_expire_at', sa.DateTime(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('last_validated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('source', sa.String(length=128), nullable=True),
    sa.Column('author', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['knowledge_base_id'], ['knowledge_base.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qa_memory_record_project_id'), 'qa_memory_record', ['project_id'], unique=False)
    op.create_table('qa_memory_event',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('qa_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['qa_id'], ['qa_memory_record.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qa_memory_event_project_id'), 'qa_memory_event', ['project_id'], unique=False)
    op.create_index(op.f('ix_qa_memory_event_qa_id'), 'qa_memory_event', ['qa_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_qa_memory_event_qa_id'), table_name='qa_memory_event')
    op.drop_index(op.f('ix_qa_memory_event_project_id'), table_name='qa_memory_event')
    op.drop_table('qa_memory_event')
    op.drop_index(op.f('ix_qa_memory_record_project_id'), table_name='qa_memory_record')
    op.drop_table('qa_memory_record')
    # ### end Alembic commands ###
