"""25

Revision ID: 7c91ec671d79
Revises: 39ba93f58818
Create Date: 2025-11-28 17:30:25.325921

"""
from typing import Sequence, Union

from alembic import op
import models as models
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c91ec671d79'
down_revision: Union[str, None] = '39ba93f58818'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge_document', sa.Column('push_status', sa.Integer(), server_default=sa.text('0'), nullable=True, comment='push status'))
    op.add_column('knowledge_document', sa.Column('push_time', sa.DateTime(), nullable=True, comment='push time'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('knowledge_document', 'push_time')
    op.drop_column('knowledge_document', 'push_status')
    # ### end Alembic commands ###
