"""28

Revision ID: 3e3d1369dd34
Revises: 6fc8c551fb9a
Create Date: 2026-01-03 07:03:04.940642

"""
from typing import Sequence, Union

from alembic import op
import models as models
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3e3d1369dd34'
down_revision: Union[str, None] = '6fc8c551fb9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_grade_record',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('prompt', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('prompt_hash', sa.String(length=150), server_default=sa.text("''"), nullable=False),
    sa.Column('task_level', sa.String(), server_default='L1', nullable=False),
    sa.Column('reason', sa.String(length=300), server_default=sa.text("''"), nullable=False),
    sa.Column('recommended_model', sa.String(length=128), server_default=sa.text("''"), nullable=False),
    sa.Column('recommended_model_provider', sa.String(length=64), server_default=sa.text("''"), nullable=False),
    sa.Column('confidence', sa.Float(), server_default=sa.text('0.5'), nullable=False),
    sa.Column('temperature', sa.Float(), server_default=sa.text('0.5'), nullable=True),
    sa.Column('top_p', sa.Float(), server_default=sa.text('0.9'), nullable=True),
    sa.Column('weight', sa.Float(), server_default=sa.text('0.5'), nullable=True),
    sa.Column('raw_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=True),
    sa.Column('raw_text', sa.Text(), server_default=sa.text("''"), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_grade_record_task_level'), 'task_grade_record', ['task_level'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_grade_record_task_level'), table_name='task_grade_record')
    op.drop_table('task_grade_record')
    # ### end Alembic commands ###
