"""30

Revision ID: 5255e589bb54
Revises: 3e3d1369dd34
Create Date: 2026-03-20 22:36:18.427415

"""
from typing import Sequence, Union

import pgvecto_rs.sqlalchemy
from alembic import op
import models as models
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5255e589bb54'
down_revision: Union[str, None] = '3e3d1369dd34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_plan',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Plan id'),
    sa.Column('agent_id', sa.Integer(), nullable=True, comment='Owning agent id'),
    sa.Column('session_id', sa.Integer(), nullable=True, comment='Associated session id'),
    sa.Column('user_id', sa.String(length=100), nullable=True, comment='Owning user id'),
    sa.Column('title', sa.String(length=500), nullable=False, comment='Plan title'),
    sa.Column('body', sa.Text(), nullable=False, comment='Markdown planning document body'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='Status: draft/active/completed/cancelled/archived'),
    sa.Column('change_log', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Audit log of plan changes'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Creation time'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Last update time'),
    sa.PrimaryKeyConstraint('id'),
    comment='Agent execution plans for supervisor task orchestration'
    )
    op.create_index('idx_agent_plan_agent_id', 'agent_plan', ['agent_id'], unique=False)
    op.create_index('idx_agent_plan_session_id', 'agent_plan', ['session_id'], unique=False)
    op.create_index('idx_agent_plan_status', 'agent_plan', ['status'], unique=False)
    op.create_index('idx_agent_plan_user_id', 'agent_plan', ['user_id'], unique=False)
    op.create_index(op.f('ix_agent_plan_id'), 'agent_plan', ['id'], unique=False)
    op.create_table('agent_todo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Todo item id'),
    sa.Column('agent_id', sa.Integer(), nullable=True, comment='Owning agent id'),
    sa.Column('session_id', sa.Integer(), nullable=True, comment='Associated session id'),
    sa.Column('user_id', sa.String(length=100), nullable=True, comment='Owning user id'),
    sa.Column('title', sa.String(length=500), nullable=False, comment='Short imperative task title'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='Status: pending/in_progress/completed/failed/blocked'),
    sa.Column('completion_condition', sa.Text(), nullable=True, comment='Concrete completion condition for this todo'),
    sa.Column('blocked_reason', sa.Text(), nullable=True, comment='Reason this todo is blocked'),
    sa.Column('failure_reason', sa.Text(), nullable=True, comment='Failure reason short string'),
    sa.Column('failure_evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Legacy structured failure evidence kept for offline failure analysis'),
    sa.Column('depends_on', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='List of todo IDs that must be completed before this todo can start'),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Structured verification evidence for completion or state transitions'),
    sa.Column('change_log', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Audit log of todo changes, including status transitions and reasons'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Creation time'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Last update time'),
    sa.PrimaryKeyConstraint('id'),
    comment='Agent todo items for supervisor task tracking'
    )
    op.create_index('idx_agent_todo_agent_id', 'agent_todo', ['agent_id'], unique=False)
    op.create_index('idx_agent_todo_session_id', 'agent_todo', ['session_id'], unique=False)
    op.create_index('idx_agent_todo_status', 'agent_todo', ['status'], unique=False)
    op.create_index('idx_agent_todo_user_id', 'agent_todo', ['user_id'], unique=False)
    op.create_index(op.f('ix_agent_todo_id'), 'agent_todo', ['id'], unique=False)
    op.create_table('cron_job',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Cron job id'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Cron display name'),
    sa.Column('message_id', sa.String(length=200), nullable=True, comment='Originating conversation message id'),
    sa.Column('user_id', sa.String(length=100), nullable=True, comment='Owning user id'),
    sa.Column('agent_id', sa.Integer(), nullable=True, comment='Owning agent id'),
    sa.Column('session_id', sa.Integer(), nullable=True, comment='Owning session id'),
    sa.Column('schedule', sa.String(length=120), nullable=False, comment='Cron expression'),
    sa.Column('timezone', sa.String(length=64), nullable=False, comment='Cron timezone'),
    sa.Column('enabled', sa.Boolean(), nullable=False, comment='Whether the schedule is active'),
    sa.Column('execution_type', sa.String(length=20), nullable=False, comment='command | shell_script | python_script'),
    sa.Column('command', sa.Text(), nullable=True, comment='Shell command text when execution_type=command'),
    sa.Column('script_path', sa.String(length=255), nullable=True, comment='Relative script path inside app.workdir'),
    sa.Column('timeout_seconds', sa.Integer(), nullable=True, comment='Execution timeout in seconds'),
    sa.Column('last_task_id', sa.Integer(), nullable=True, comment='Last created task job id'),
    sa.Column('last_run_at', sa.DateTime(), nullable=True, comment='Last trigger time'),
    sa.Column('next_run_at', sa.DateTime(), nullable=True, comment='Next trigger time'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Creation time'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Last update time'),
    sa.PrimaryKeyConstraint('id'),
    comment='Persisted scheduled task definitions'
    )
    op.create_index('idx_cron_job_enabled', 'cron_job', ['enabled'], unique=False)
    op.create_index('idx_cron_job_next_run_at', 'cron_job', ['next_run_at'], unique=False)
    op.create_index('idx_cron_job_updated_at', 'cron_job', ['updated_at'], unique=False)
    op.create_index(op.f('ix_cron_job_id'), 'cron_job', ['id'], unique=False)
    op.create_table('event_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Row id'),
    sa.Column('event_id', sa.UUID(), nullable=False, comment='Globally unique event identifier (UUID v4)'),
    sa.Column('session_id', sa.String(length=200), nullable=True, comment='Session associated with the event'),
    sa.Column('request_id', sa.String(length=200), nullable=True, comment='Request/execution ID associated with the event'),
    sa.Column('event_type', sa.String(length=60), nullable=False, comment='request_received | intent_analyzed | context_built | capability_selected | plan_created | plan_criticized | todo_created | todo_started | todo_completed | todo_failed | retry_triggered | replan_triggered | response_composed | memory_written'),
    sa.Column('actor', sa.String(length=200), nullable=True, comment='Agent or component that emitted the event'),
    sa.Column('target_id', sa.String(length=200), nullable=True, comment='ID of the entity affected (todo_id, plan_id, etc.)'),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Arbitrary structured data for this event'),
    sa.Column('timestamp', sa.DateTime(), nullable=False, comment='Wall-clock time when the event occurred'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id'),
    comment='Append-only audit trail of all orchestration events'
    )
    op.create_index('idx_event_log_event_type', 'event_logs', ['event_type'], unique=False)
    op.create_index('idx_event_log_request_id', 'event_logs', ['request_id'], unique=False)
    op.create_index('idx_event_log_session_id', 'event_logs', ['session_id'], unique=False)
    op.create_index('idx_event_log_timestamp', 'event_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_event_logs_id'), 'event_logs', ['id'], unique=False)
    op.create_table('execution_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Row id'),
    sa.Column('todo_id', sa.Integer(), nullable=True, comment='Associated AgentTodo id'),
    sa.Column('plan_id', sa.Integer(), nullable=True, comment='Associated AgentPlan id'),
    sa.Column('session_id', sa.String(length=200), nullable=True, comment='Session id of the execution'),
    sa.Column('agent_id', sa.Integer(), nullable=True, comment='Agent that executed the capability'),
    sa.Column('capability_type', sa.String(length=20), nullable=True, comment='tool | skill | agent | workflow | mcp'),
    sa.Column('capability_name', sa.String(length=200), nullable=True, comment='Name of the capability used'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='success | partial | failed'),
    sa.Column('input_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Input sent to the capability'),
    sa.Column('output_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Output returned by the capability'),
    sa.Column('observation', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Structured observation: evidence[] and artifacts[]'),
    sa.Column('success_criteria_check', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Success criteria evaluation results'),
    sa.Column('started_at', sa.DateTime(), nullable=True, comment='Execution start time'),
    sa.Column('ended_at', sa.DateTime(), nullable=True, comment='Execution end time'),
    sa.Column('latency_ms', sa.Float(), nullable=True, comment='Execution latency in milliseconds'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Record creation time'),
    sa.PrimaryKeyConstraint('id'),
    comment='Logs each todo execution attempt for observability and reflection'
    )
    op.create_index('idx_execution_record_plan_id', 'execution_records', ['plan_id'], unique=False)
    op.create_index('idx_execution_record_session_id', 'execution_records', ['session_id'], unique=False)
    op.create_index('idx_execution_record_status', 'execution_records', ['status'], unique=False)
    op.create_index('idx_execution_record_todo_id', 'execution_records', ['todo_id'], unique=False)
    op.create_index(op.f('ix_execution_records_id'), 'execution_records', ['id'], unique=False)
    op.create_table('failure_pattern',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('pattern_type', sa.String(length=100), nullable=False),
    sa.Column('pattern_hash', sa.String(length=64), nullable=False),
    sa.Column('occurrence_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=True),
    sa.Column('repair_strategy', sa.Text(), nullable=True),
    sa.Column('effectiveness', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pattern_hash'),
    comment='Aggregated failure evidence and repair strategies'
    )
    op.create_index('idx_failure_pattern_user_type', 'failure_pattern', ['user_id', 'pattern_type'], unique=False)
    op.create_table('learning_signal',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('agent_id', sa.String(length=100), nullable=True),
    sa.Column('signal_type', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.String(length=100), nullable=True),
    sa.Column('value', sa.Float(), server_default=sa.text('0.0'), nullable=False),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    comment='Unified signal event stream for memory quality learning'
    )
    op.create_index('idx_learning_signal_source_id', 'learning_signal', ['source_id'], unique=False)
    op.create_index('idx_learning_signal_user_type_created', 'learning_signal', ['user_id', 'signal_type', 'created_at'], unique=False)
    op.create_table('memory_learning_log',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False, comment='用户ID'),
    sa.Column('quality_scored', sa.Integer(), nullable=True, comment='本轮打分记忆条数'),
    sa.Column('insights_created', sa.Integer(), nullable=True, comment='本轮生成洞察数'),
    sa.Column('merges_performed', sa.Integer(), nullable=True, comment='本轮合并主题数'),
    sa.Column('memories_pruned', sa.Integer(), nullable=True, comment='本轮剪枝记忆数'),
    sa.Column('elapsed_seconds', sa.Float(), nullable=True, comment='本轮耗时秒数'),
    sa.Column('error', sa.String(length=500), nullable=True, comment='错误信息，无错误则 NULL'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_memory_learning_log_user_created', 'memory_learning_log', ['user_id', 'created_at'], unique=False)
    op.create_table('memory_learning_params',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False, comment='用户ID'),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='各组件参数，结构见 ParamOptimizer.DEFAULT_PARAMS'),
    sa.Column('reasoning', sa.Text(), nullable=True, comment='LLM 给出的调参理由'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_memory_learning_params_user_created', 'memory_learning_params', ['user_id', 'created_at'], unique=False)
    op.create_table('memory_retrieval_log',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('agent_id', sa.String(length=100), nullable=True),
    sa.Column('project_id', sa.String(length=100), nullable=True),
    sa.Column('retrieve_type', sa.String(length=10), nullable=False, comment='rag | llm'),
    sa.Column('top_k', sa.SmallInteger(), nullable=False),
    sa.Column('query_hash', sa.String(length=16), nullable=False, comment='SHA256(query)[:16]'),
    sa.Column('ms_domain_count', sa.SmallInteger(), nullable=True),
    sa.Column('ms_topic_count', sa.SmallInteger(), nullable=True),
    sa.Column('latency_step0_ms', sa.Integer(), nullable=True),
    sa.Column('sub_query_count', sa.SmallInteger(), nullable=True),
    sa.Column('sub_query_failed', sa.Boolean(), nullable=True),
    sa.Column('latency_step1_ms', sa.Integer(), nullable=True),
    sa.Column('sub_query_stats', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='[{query_hash, candidate_count, ...}]'),
    sa.Column('candidate_total_raw', sa.Integer(), nullable=True),
    sa.Column('candidate_total_unique', sa.Integer(), nullable=True),
    sa.Column('multi_hit_count', sa.Integer(), nullable=True),
    sa.Column('multi_hit_max', sa.SmallInteger(), nullable=True),
    sa.Column('latency_step2_ms', sa.Integer(), nullable=True),
    sa.Column('judge_input_count', sa.Integer(), nullable=True),
    sa.Column('judge_output_count', sa.Integer(), nullable=True),
    sa.Column('judge_selection_rate', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('judge_failed', sa.Boolean(), nullable=True),
    sa.Column('latency_step3_ms', sa.Integer(), nullable=True),
    sa.Column('final_count', sa.SmallInteger(), nullable=True),
    sa.Column('final_score_avg', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('final_score_p50', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('final_score_p10', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('domain_dist', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source_dist', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('type_dist', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('latency_total_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('memory_retrieval_result',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('log_id', sa.UUID(), nullable=False),
    sa.Column('memory_id', sa.UUID(), nullable=False),
    sa.Column('hit_count', sa.SmallInteger(), nullable=True, comment='被几条子查询命中'),
    sa.Column('rag_score', sa.Numeric(precision=5, scale=4), nullable=True, comment='LLM 融合前的原始向量 score'),
    sa.Column('from_expansion', sa.Boolean(), nullable=True, comment='来自图谱邻居扩展'),
    sa.Column('judge_rank', sa.SmallInteger(), nullable=True, comment='LLM judge 排序位，NULL=未入选 judge 输出'),
    sa.Column('final_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('final_rank', sa.SmallInteger(), nullable=True, comment='最终结果位置，NULL=未进入最终结果'),
    sa.Column('memory_domain', sa.String(length=50), nullable=True),
    sa.Column('memory_type', sa.String(length=32), nullable=True),
    sa.Column('memory_source', sa.String(length=50), nullable=True),
    sa.Column('access_count_at_query', sa.Integer(), nullable=True, comment='查询时刻的 access_count 快照'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Row id'),
    sa.Column('agent_id', sa.Integer(), nullable=False, comment='Agent this permission applies to'),
    sa.Column('scope', sa.String(length=100), nullable=False, comment='Permission scope: agent | role:<name> | global'),
    sa.Column('allowed_tool_names', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Tool names the agent is explicitly allowed to invoke: []'),
    sa.Column('denied_tool_names', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Tool names the agent is explicitly denied from invoking: []'),
    sa.Column('reason', sa.Text(), nullable=True, comment='Human-readable rationale for this permission entry'),
    sa.Column('granted_by', sa.String(length=200), nullable=True, comment='User or system that granted this permission'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Record creation time'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Last update time'),
    sa.PrimaryKeyConstraint('id'),
    comment='Agent-level tool permission grants and denials'
    )
    op.create_index('idx_permission_agent_id', 'permissions', ['agent_id'], unique=False)
    op.create_index('idx_permission_scope', 'permissions', ['scope'], unique=False)
    op.create_index(op.f('ix_permissions_id'), 'permissions', ['id'], unique=False)
    op.create_table('stored_responses',
    sa.Column('id', sa.String(length=255), nullable=False, comment='Response ID, e.g. resp_xxx'),
    sa.Column('model', sa.String(length=255), nullable=False, comment='Model name used for this response'),
    sa.Column('previous_response_id', sa.String(length=255), nullable=True, comment='ID of the preceding response in this conversation chain'),
    sa.Column('input_items', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False, comment='Full effective input sent to the model (includes all prior context)'),
    sa.Column('output_items', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False, comment='Output items returned by the model'),
    sa.Column('usage', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Token usage statistics'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Creation timestamp'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stored_responses_model'), 'stored_responses', ['model'], unique=False)
    op.create_index(op.f('ix_stored_responses_previous_response_id'), 'stored_responses', ['previous_response_id'], unique=False)
    op.create_table('task_cost_record',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('agent_id', sa.String(length=100), nullable=True),
    sa.Column('todo_id', sa.UUID(), nullable=True),
    sa.Column('task_level', sa.String(length=10), nullable=True),
    sa.Column('task_type', sa.String(length=100), nullable=True),
    sa.Column('model_id', sa.String(length=128), nullable=True),
    sa.Column('provider', sa.String(length=64), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('total_price', sa.DECIMAL(precision=10, scale=7), nullable=True),
    sa.Column('outcome', sa.String(length=20), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    comment='Per-task cost and outcome records for cost-aware routing'
    )
    op.create_index('idx_task_cost_record_created_at', 'task_cost_record', ['created_at'], unique=False)
    op.create_index('idx_task_cost_record_task_level', 'task_cost_record', ['task_level'], unique=False)
    op.create_index('idx_task_cost_record_user_model', 'task_cost_record', ['user_id', 'model_id'], unique=False)
    op.create_table('task_job',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Task job id'),
    sa.Column('name', sa.String(length=255), nullable=True, comment='Optional task display name'),
    sa.Column('source', sa.String(length=20), nullable=False, comment='manual | cron'),
    sa.Column('cron_id', sa.Integer(), nullable=True, comment='Source cron job id when created by scheduler'),
    sa.Column('message_id', sa.String(length=200), nullable=True, comment='Originating conversation message id'),
    sa.Column('user_id', sa.String(length=100), nullable=True, comment='Owning user id'),
    sa.Column('agent_id', sa.Integer(), nullable=True, comment='Owning agent id'),
    sa.Column('session_id', sa.Integer(), nullable=True, comment='Owning session id'),
    sa.Column('execution_type', sa.String(length=20), nullable=False, comment='command | shell_script | python_script'),
    sa.Column('command', sa.Text(), nullable=True, comment='Shell command text when execution_type=command'),
    sa.Column('script_path', sa.String(length=255), nullable=True, comment='Relative script path inside app.workdir'),
    sa.Column('timeout_seconds', sa.Integer(), nullable=True, comment='Execution timeout in seconds'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='pending | running | completed | failed | cancelled'),
    sa.Column('output_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Execution output payload'),
    sa.Column('error', sa.Text(), nullable=True, comment='Execution error'),
    sa.Column('celery_task_id', sa.String(length=120), nullable=True, comment='Backing Celery task id'),
    sa.Column('cancellation_requested', sa.Boolean(), nullable=False, comment='Cancellation requested flag'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Creation time'),
    sa.Column('started_at', sa.DateTime(), nullable=True, comment='Execution start time'),
    sa.Column('finished_at', sa.DateTime(), nullable=True, comment='Execution end time'),
    sa.Column('cancel_requested_at', sa.DateTime(), nullable=True, comment='Cancellation request time'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Last update time'),
    sa.PrimaryKeyConstraint('id'),
    comment='Persisted background task jobs'
    )
    op.create_index('idx_task_job_celery_task_id', 'task_job', ['celery_task_id'], unique=False)
    op.create_index('idx_task_job_created_at', 'task_job', ['created_at'], unique=False)
    op.create_index('idx_task_job_cron_id', 'task_job', ['cron_id'], unique=False)
    op.create_index('idx_task_job_status', 'task_job', ['status'], unique=False)
    op.create_index(op.f('ix_task_job_id'), 'task_job', ['id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False, comment='user id'),
    sa.Column('username', sa.String(), nullable=False, comment='username'),
    sa.Column('password_hash', sa.String(), nullable=False, comment='bcrypt password hash'),
    sa.Column('email', sa.String(), nullable=True, comment='user email'),
    sa.Column('role', sa.String(), nullable=True, comment='user role: admin or user'),
    sa.Column('status', sa.String(), nullable=True, comment='user status: active or disabled'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='user create time'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='user update time'),
    sa.Column('deleted', sa.Integer(), nullable=True, comment='user delete flag'),
    sa.PrimaryKeyConstraint('id'),
    comment='user table'
    )
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.add_column('agent', sa.Column('output_schema', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'"), nullable=True, comment='Output schema'))
    op.add_column('agent', sa.Column('user_id', sa.String(length=100), nullable=True, comment='User ID'))
    op.alter_column('agent', 'enabled_memory',
               existing_type=sa.INTEGER(),
               comment='Enable memory,user agent disabled by default',
               existing_comment='Enable memory',
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.add_column('agent_session', sa.Column('user_id', sa.String(length=100), nullable=True, comment='User ID'))
    op.create_index(op.f('ix_agent_session_user_id'), 'agent_session', ['user_id'], unique=False)
    op.add_column('api_key_info', sa.Column('user_id', sa.Integer(), nullable=True, comment='bound user id'))
    op.create_index(op.f('ix_api_key_info_user_id'), 'api_key_info', ['user_id'], unique=False)
    op.create_foreign_key(None, 'api_key_info', 'user', ['user_id'], ['id'])
    op.add_column('conversation_message', sa.Column('user_id', sa.String(length=100), server_default=sa.text("''"), nullable=True, comment='user id'))
    op.create_index(op.f('ix_conversation_message_user_id'), 'conversation_message', ['user_id'], unique=False)
    op.add_column('knowledge_base', sa.Column('user_id', sa.String(length=100), nullable=True, comment='owner user id'))
    op.add_column('knowledge_document', sa.Column('user_id', sa.String(length=100), nullable=True, comment='owner user id'))
    op.add_column('memory_base', sa.Column('mem_kb_id', sa.String(length=100), nullable=True, comment='关联的知识库ID'))
    op.add_column('memory_base', sa.Column('type', sa.String(length=32), nullable=False))
    op.add_column('memory_base', sa.Column('deleted', sa.Integer(), nullable=True, comment='delete flag'))
    op.drop_column('memory_base', 'mem_kb_mapping')
    op.drop_column('memory_base', 'project_id')
    op.drop_column('memory_base', 'agent_id')
    op.add_column('memory_record', sa.Column('user_id', sa.String(length=100), nullable=True, comment='代理ID'))
    op.add_column('memory_record', sa.Column('topic', sa.String(), server_default=sa.text("''"), nullable=True))
    op.add_column('memory_record', sa.Column('quality_score', sa.Float(), nullable=True, comment='质量分数 0-1，由学习引擎定期更新'))
    op.add_column('memory_record', sa.Column('deleted', sa.Integer(), nullable=True, comment='delete flag'))
    op.alter_column('memory_record', 'access_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               comment='被检索次数，检索时自增')
    op.drop_index(op.f('idx_memory_importance'), table_name='memory_record')
    op.create_index('idx_memory_topic', 'memory_record', ['topic'], unique=False)
    op.drop_column('memory_record', 'topic_id')
    op.drop_column('memory_record', 'importance')
    op.drop_column('memory_record', 'level')
    op.drop_column('memory_record', 'extra')
    op.drop_column('memory_record', 'ttl')
    op.drop_column('memory_tag_associations', 'confidence')
    op.add_column('message_token_usage', sa.Column('cached_prompt_tokens', sa.Integer(), server_default=sa.text("'0'"), nullable=False, comment='number of cached prompt tokens'))
    op.add_column('message_token_usage', sa.Column('thinking_tokens', sa.Integer(), server_default=sa.text("'0'"), nullable=False, comment='number of thinking tokens'))
    op.add_column('message_token_usage', sa.Column('thinking_price', sa.DECIMAL(precision=10, scale=7), server_default=sa.text("'0.0000000'"), nullable=False, comment='thinking price'))
    op.add_column('message_token_usage', sa.Column('cache_price', sa.DECIMAL(precision=10, scale=7), server_default=sa.text("'0.0000000'"), nullable=False, comment='cache price'))
    op.add_column('model', sa.Column('max_context_length', sa.Integer(), server_default=sa.text("'0'"), nullable=True, comment='Max Context Length'))
    op.add_column('model', sa.Column('cache_read_price', sa.DECIMAL(precision=10, scale=7), server_default=sa.text("'0.0000000'"), nullable=True, comment='Cache Read Price'))
    op.add_column('model', sa.Column('cache_write_price', sa.DECIMAL(precision=10, scale=7), server_default=sa.text("'0.0000000'"), nullable=True, comment='Cache Write Price'))
    op.add_column('model', sa.Column('thinking_price', sa.DECIMAL(precision=10, scale=7), server_default=sa.text("'0.0000000'"), nullable=True, comment='Thinking Price'))
    op.create_index(op.f('ix_model_max_context_length'), 'model', ['max_context_length'], unique=False)
    op.create_index('idx_task_grade_record_task_level', 'task_grade_record', ['task_level'], unique=False)
    op.create_table_comment(
        'task_grade_record',
        'Records task complexity grading decisions for model routing',
        existing_comment=None,
        schema=None
    )
    op.add_column('tool_call_result', sa.Column('tool_call_name', sa.String(), nullable=True, comment='tool call name'))
    op.add_column('tool_call_result', sa.Column('tool_call_args', sa.String(), nullable=True, comment='tool call arguments'))
    op.drop_index(op.f('ix_tool_call_result_tool_id'), table_name='tool_call_result')
    op.create_index(op.f('ix_tool_call_result_tool_call_args'), 'tool_call_result', ['tool_call_args'], unique=False)
    op.create_index(op.f('ix_tool_call_result_tool_call_name'), 'tool_call_result', ['tool_call_name'], unique=False)
    op.drop_constraint(op.f('tool_call_result_tool_id_fkey'), 'tool_call_result', type_='foreignkey')
    op.drop_column('tool_call_result', 'tool_call')
    op.drop_column('tool_call_result', 'tool_id')
    op.add_column('tool_info', sa.Column('mcp_server_url', sa.String(), server_default=sa.text("''"), nullable=True, comment='mcp server url'))
    op.drop_column('tool_info', 'mcp_server_code')
    op.add_column('user_custom_tags', sa.Column('vector', pgvecto_rs.sqlalchemy.vector.VECTOR(4096), nullable=True, comment='embedding vector'))
    op.create_index('idx_mem_tag_vector', 'user_custom_tags', ['vector'], unique=False, postgresql_using='vectors', postgresql_with={'options': '$$optimizing.optimizing_threads = 30\n                                    segment.max_growing_segment_size = 2000\n                                    segment.max_sealed_segment_size = 30000000\n                                    [indexing.hnsw]\n                                    m=30\n                                    ef_construction=500$$'}, postgresql_ops={'vector': 'vector_l2_ops'})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_mem_tag_vector', table_name='user_custom_tags', postgresql_using='vectors', postgresql_with={'options': '$$optimizing.optimizing_threads = 30\n                                    segment.max_growing_segment_size = 2000\n                                    segment.max_sealed_segment_size = 30000000\n                                    [indexing.hnsw]\n                                    m=30\n                                    ef_construction=500$$'}, postgresql_ops={'vector': 'vector_l2_ops'})
    op.drop_column('user_custom_tags', 'vector')
    op.add_column('tool_info', sa.Column('mcp_server_code', sa.VARCHAR(), server_default=sa.text("''::character varying"), autoincrement=False, nullable=True, comment='mcp server code'))
    op.drop_column('tool_info', 'mcp_server_url')
    op.add_column('tool_call_result', sa.Column('tool_id', sa.UUID(), autoincrement=False, nullable=True, comment='tool id'))
    op.add_column('tool_call_result', sa.Column('tool_call', sa.TEXT(), autoincrement=False, nullable=True, comment='tool calls'))
    op.create_foreign_key(op.f('tool_call_result_tool_id_fkey'), 'tool_call_result', 'tool_info', ['tool_id'], ['id'])
    op.drop_index(op.f('ix_tool_call_result_tool_call_name'), table_name='tool_call_result')
    op.drop_index(op.f('ix_tool_call_result_tool_call_args'), table_name='tool_call_result')
    op.create_index(op.f('ix_tool_call_result_tool_id'), 'tool_call_result', ['tool_id'], unique=False)
    op.drop_column('tool_call_result', 'tool_call_args')
    op.drop_column('tool_call_result', 'tool_call_name')
    op.drop_table_comment(
        'task_grade_record',
        existing_comment='Records task complexity grading decisions for model routing',
        schema=None
    )
    op.drop_index('idx_task_grade_record_task_level', table_name='task_grade_record')
    op.drop_index(op.f('ix_model_max_context_length'), table_name='model')
    op.drop_column('model', 'thinking_price')
    op.drop_column('model', 'cache_write_price')
    op.drop_column('model', 'cache_read_price')
    op.drop_column('model', 'max_context_length')
    op.drop_column('message_token_usage', 'cache_price')
    op.drop_column('message_token_usage', 'thinking_price')
    op.drop_column('message_token_usage', 'thinking_tokens')
    op.drop_column('message_token_usage', 'cached_prompt_tokens')
    op.add_column('memory_tag_associations', sa.Column('confidence', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('memory_record', sa.Column('ttl', sa.INTEGER(), autoincrement=False, nullable=True, comment='TTL in seconds'))
    op.add_column('memory_record', sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False, comment='Residual metadata'))
    op.add_column('memory_record', sa.Column('level', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('memory_record', sa.Column('importance', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0.5'), autoincrement=False, nullable=False))
    op.add_column('memory_record', sa.Column('topic_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_index('idx_memory_topic', table_name='memory_record')
    op.create_index(op.f('idx_memory_importance'), 'memory_record', ['importance'], unique=False)
    op.alter_column('memory_record', 'access_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               comment=None,
               existing_comment='被检索次数，检索时自增')
    op.drop_column('memory_record', 'deleted')
    op.drop_column('memory_record', 'quality_score')
    op.drop_column('memory_record', 'topic')
    op.drop_column('memory_record', 'user_id')
    op.add_column('memory_base', sa.Column('agent_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True, comment='代理ID'))
    op.add_column('memory_base', sa.Column('project_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True, comment='项目ID'))
    op.add_column('memory_base', sa.Column('mem_kb_mapping', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False, comment='记忆与知识库映射关系,格式为 {MemoryDomain: KnowledgeBaseID}'))
    op.drop_column('memory_base', 'deleted')
    op.drop_column('memory_base', 'type')
    op.drop_column('memory_base', 'mem_kb_id')
    op.drop_column('knowledge_document', 'user_id')
    op.drop_column('knowledge_base', 'user_id')
    op.drop_index(op.f('ix_conversation_message_user_id'), table_name='conversation_message')
    op.drop_column('conversation_message', 'user_id')
    op.drop_constraint(None, 'api_key_info', type_='foreignkey')
    op.drop_index(op.f('ix_api_key_info_user_id'), table_name='api_key_info')
    op.drop_column('api_key_info', 'user_id')
    op.drop_index(op.f('ix_agent_session_user_id'), table_name='agent_session')
    op.drop_column('agent_session', 'user_id')
    op.alter_column('agent', 'enabled_memory',
               existing_type=sa.INTEGER(),
               comment='Enable memory',
               existing_comment='Enable memory,user agent disabled by default',
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_column('agent', 'user_id')
    op.drop_column('agent', 'output_schema')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_task_job_id'), table_name='task_job')
    op.drop_index('idx_task_job_status', table_name='task_job')
    op.drop_index('idx_task_job_cron_id', table_name='task_job')
    op.drop_index('idx_task_job_created_at', table_name='task_job')
    op.drop_index('idx_task_job_celery_task_id', table_name='task_job')
    op.drop_table('task_job')
    op.drop_index('idx_task_cost_record_user_model', table_name='task_cost_record')
    op.drop_index('idx_task_cost_record_task_level', table_name='task_cost_record')
    op.drop_index('idx_task_cost_record_created_at', table_name='task_cost_record')
    op.drop_table('task_cost_record')
    op.drop_index(op.f('ix_stored_responses_previous_response_id'), table_name='stored_responses')
    op.drop_index(op.f('ix_stored_responses_model'), table_name='stored_responses')
    op.drop_table('stored_responses')
    op.drop_index(op.f('ix_permissions_id'), table_name='permissions')
    op.drop_index('idx_permission_scope', table_name='permissions')
    op.drop_index('idx_permission_agent_id', table_name='permissions')
    op.drop_table('permissions')
    op.drop_table('memory_retrieval_result')
    op.drop_table('memory_retrieval_log')
    op.drop_index('idx_memory_learning_params_user_created', table_name='memory_learning_params')
    op.drop_table('memory_learning_params')
    op.drop_index('idx_memory_learning_log_user_created', table_name='memory_learning_log')
    op.drop_table('memory_learning_log')
    op.drop_index('idx_learning_signal_user_type_created', table_name='learning_signal')
    op.drop_index('idx_learning_signal_source_id', table_name='learning_signal')
    op.drop_table('learning_signal')
    op.drop_index('idx_failure_pattern_user_type', table_name='failure_pattern')
    op.drop_table('failure_pattern')
    op.drop_index(op.f('ix_execution_records_id'), table_name='execution_records')
    op.drop_index('idx_execution_record_todo_id', table_name='execution_records')
    op.drop_index('idx_execution_record_status', table_name='execution_records')
    op.drop_index('idx_execution_record_session_id', table_name='execution_records')
    op.drop_index('idx_execution_record_plan_id', table_name='execution_records')
    op.drop_table('execution_records')
    op.drop_index(op.f('ix_event_logs_id'), table_name='event_logs')
    op.drop_index('idx_event_log_timestamp', table_name='event_logs')
    op.drop_index('idx_event_log_session_id', table_name='event_logs')
    op.drop_index('idx_event_log_request_id', table_name='event_logs')
    op.drop_index('idx_event_log_event_type', table_name='event_logs')
    op.drop_table('event_logs')
    op.drop_index(op.f('ix_cron_job_id'), table_name='cron_job')
    op.drop_index('idx_cron_job_updated_at', table_name='cron_job')
    op.drop_index('idx_cron_job_next_run_at', table_name='cron_job')
    op.drop_index('idx_cron_job_enabled', table_name='cron_job')
    op.drop_table('cron_job')
    op.drop_index(op.f('ix_agent_todo_id'), table_name='agent_todo')
    op.drop_index('idx_agent_todo_user_id', table_name='agent_todo')
    op.drop_index('idx_agent_todo_status', table_name='agent_todo')
    op.drop_index('idx_agent_todo_session_id', table_name='agent_todo')
    op.drop_index('idx_agent_todo_agent_id', table_name='agent_todo')
    op.drop_table('agent_todo')
    op.drop_index(op.f('ix_agent_plan_id'), table_name='agent_plan')
    op.drop_index('idx_agent_plan_user_id', table_name='agent_plan')
    op.drop_index('idx_agent_plan_status', table_name='agent_plan')
    op.drop_index('idx_agent_plan_session_id', table_name='agent_plan')
    op.drop_index('idx_agent_plan_agent_id', table_name='agent_plan')
    op.drop_table('agent_plan')
    # ### end Alembic commands ###
