"""Add custom tags models

Revision ID: 0c2f5e4da428
Revises: task_cache_001
Create Date: 2026-02-26 13:49:40.937712

"""
from typing import Sequence, Union

from alembic import op
import models as models
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c2f5e4da428'
down_revision: Union[str, None] = 'task_cache_001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_custom_tags',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['user_custom_tags.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_user_tag_name')
    )
    op.create_index('idx_user_tags_active', 'user_custom_tags', ['is_active'], unique=False)
    op.create_index('idx_user_tags_parent', 'user_custom_tags', ['parent_id'], unique=False)
    op.create_index('idx_user_tags_user_id', 'user_custom_tags', ['user_id'], unique=False)
    op.create_table('memory_tag_associations',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('memory_id', sa.String(length=100), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.Column('assigned_by', sa.String(length=100), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('context', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['tag_id'], ['user_custom_tags.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('memory_id', 'tag_id', name='uq_memory_tag')
    )
    op.create_index('idx_memory_tags_assigned_by', 'memory_tag_associations', ['assigned_by'], unique=False)
    op.create_index('idx_memory_tags_memory_id', 'memory_tag_associations', ['memory_id'], unique=False)
    op.create_index('idx_memory_tags_source', 'memory_tag_associations', ['source'], unique=False)
    op.create_index('idx_memory_tags_tag_id', 'memory_tag_associations', ['tag_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_memory_tags_tag_id', table_name='memory_tag_associations')
    op.drop_index('idx_memory_tags_source', table_name='memory_tag_associations')
    op.drop_index('idx_memory_tags_memory_id', table_name='memory_tag_associations')
    op.drop_index('idx_memory_tags_assigned_by', table_name='memory_tag_associations')
    op.drop_table('memory_tag_associations')
    op.drop_index('idx_user_tags_user_id', table_name='user_custom_tags')
    op.drop_index('idx_user_tags_parent', table_name='user_custom_tags')
    op.drop_index('idx_user_tags_active', table_name='user_custom_tags')
    op.drop_table('user_custom_tags')
    # ### end Alembic commands ###
