"""34

Revision ID: 4b652c809611
Revises: c4b1a9e2f7d3
Create Date: 2026-05-03 12:32:51.221370

"""
from typing import Sequence, Union

from alembic import op
import models as models
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4b652c809611'
down_revision: Union[str, None] = 'c4b1a9e2f7d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='auth audit log id'),
    sa.Column('event', sa.String(length=128), nullable=False, comment='audit event code'),
    sa.Column('level', sa.String(length=32), nullable=False, comment='logging level name'),
    sa.Column('trace_id', sa.String(length=128), nullable=True, comment='request trace id'),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='related user id'),
    sa.Column('username', sa.String(length=128), nullable=True, comment='related username'),
    sa.Column('refresh_jti', sa.String(length=128), nullable=True, comment='related refresh token jti'),
    sa.Column('client_type', sa.String(length=32), nullable=True, comment='client type'),
    sa.Column('device_label', sa.String(length=128), nullable=True, comment='device label'),
    sa.Column('request_ip', sa.String(length=128), nullable=True, comment='request ip'),
    sa.Column('user_agent', sa.Text(), nullable=True, comment='user agent'),
    sa.Column('reason', sa.Text(), nullable=True, comment='failure or audit reason'),
    sa.Column('roles', sa.Text(), nullable=True, comment='serialized roles'),
    sa.Column('permissions', sa.Text(), nullable=True, comment='serialized permissions'),
    sa.Column('details', sa.Text(), nullable=True, comment='serialized extra details'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='audit create time'),
    sa.PrimaryKeyConstraint('id'),
    comment='auth audit log table'
    )
    op.create_index('idx_auth_audit_log_created_at', 'auth_audit_log', ['created_at'], unique=False)
    op.create_index('idx_auth_audit_log_event', 'auth_audit_log', ['event'], unique=False)
    op.create_index('idx_auth_audit_log_user_id', 'auth_audit_log', ['user_id'], unique=False)
    op.create_index(op.f('ix_auth_audit_log_id'), 'auth_audit_log', ['id'], unique=False)
    op.create_table('auth_permission',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='permission id'),
    sa.Column('code', sa.String(length=128), nullable=False, comment='permission code'),
    sa.Column('name', sa.String(length=128), nullable=False, comment='permission name'),
    sa.Column('description', sa.Text(), nullable=True, comment='permission description'),
    sa.Column('group_name', sa.String(length=128), nullable=True, comment='permission group name'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='permission create time'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='permission update time'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_auth_permission_code'),
    comment='auth permission table'
    )
    op.create_index(op.f('ix_auth_permission_code'), 'auth_permission', ['code'], unique=False)
    op.create_index(op.f('ix_auth_permission_id'), 'auth_permission', ['id'], unique=False)
    op.create_table('auth_refresh_session',
    sa.Column('id', sa.Integer(), nullable=False, comment='refresh session id'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='user id'),
    sa.Column('token_jti', sa.String(), nullable=False, comment='refresh token jti'),
    sa.Column('refresh_token_hash', sa.String(), nullable=False, comment='sha256 hash of the refresh token'),
    sa.Column('status', sa.String(), nullable=False, comment='session status: active/revoked/expired'),
    sa.Column('client_type', sa.String(), nullable=True, comment='client type, e.g. web/desktop'),
    sa.Column('device_label', sa.String(), nullable=True, comment='optional device label'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='session create time'),
    sa.Column('expires_at', sa.DateTime(), nullable=False, comment='refresh token expiry time'),
    sa.Column('last_used_at', sa.DateTime(), nullable=True, comment='last successful refresh time'),
    sa.Column('revoked_at', sa.DateTime(), nullable=True, comment='session revoked time'),
    sa.PrimaryKeyConstraint('id'),
    comment='refresh-token sessions that support revoke and rotation'
    )
    op.create_index(op.f('ix_auth_refresh_session_id'), 'auth_refresh_session', ['id'], unique=False)
    op.create_index(op.f('ix_auth_refresh_session_token_jti'), 'auth_refresh_session', ['token_jti'], unique=True)
    op.create_index(op.f('ix_auth_refresh_session_user_id'), 'auth_refresh_session', ['user_id'], unique=False)
    op.create_index('ix_auth_refresh_session_user_status', 'auth_refresh_session', ['user_id', 'status'], unique=False)
    op.create_table('auth_role',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='role id'),
    sa.Column('code', sa.String(length=64), nullable=False, comment='role code'),
    sa.Column('name', sa.String(length=128), nullable=False, comment='role name'),
    sa.Column('description', sa.Text(), nullable=True, comment='role description'),
    sa.Column('status', sa.String(length=32), nullable=False, comment='role status: active or disabled'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='role create time'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='role update time'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_auth_role_code'),
    comment='auth role table'
    )
    op.create_index(op.f('ix_auth_role_code'), 'auth_role', ['code'], unique=False)
    op.create_index(op.f('ix_auth_role_id'), 'auth_role', ['id'], unique=False)
    op.create_table('memory_conversation',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('conversation_id', sa.String(length=191), nullable=False, comment='Canonical conversation id'),
    sa.Column('external_source', sa.String(length=64), nullable=False, comment='External conversation source'),
    sa.Column('external_session_id', sa.String(length=191), nullable=False, comment='External source session id'),
    sa.Column('user_id', sa.String(length=100), nullable=False, comment='Owning user id'),
    sa.Column('agent_id', sa.String(length=100), nullable=True, comment='Owning agent id'),
    sa.Column('project_id', sa.String(length=255), nullable=True, comment='Project id'),
    sa.Column('title', sa.String(length=500), nullable=True, comment='Conversation title'),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False, comment='Conversation-level metadata'),
    sa.Column('message_store_type', sa.String(length=32), server_default=sa.text("'jsonl'"), nullable=False, comment='Message storage type'),
    sa.Column('message_store_uri', sa.String(length=1024), nullable=False, comment='Authoritative jsonl locator'),
    sa.Column('message_store_path', sa.String(length=1024), nullable=True, comment='Optional filesystem-compatible display path'),
    sa.Column('message_count', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='Count of message rows in the jsonl object'),
    sa.Column('modalities', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False, comment='Union of message content part types'),
    sa.Column('content_sha256', sa.String(length=64), nullable=True, comment='Hash of current jsonl content'),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True, comment='Size of current jsonl object in bytes'),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False, comment='Monotonic conversation version'),
    sa.Column('status', sa.String(length=32), server_default=sa.text("'active'"), nullable=False, comment='Conversation resource status'),
    sa.Column('first_message_at', sa.DateTime(), nullable=True, comment='Timestamp of first message'),
    sa.Column('last_message_at', sa.DateTime(), nullable=True, comment='Timestamp of latest message'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='Creation time'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='Last update time'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Soft delete timestamp'),
    sa.PrimaryKeyConstraint('id'),
    comment='Programmer memory conversation metadata with external jsonl message storage'
    )
    op.create_index('idx_memory_conversation_last_message_at', 'memory_conversation', ['last_message_at'], unique=False)
    op.create_index('idx_memory_conversation_project_updated_at', 'memory_conversation', ['project_id', 'updated_at'], unique=False)
    op.create_index('idx_memory_conversation_status', 'memory_conversation', ['status'], unique=False)
    op.create_index('idx_memory_conversation_user_updated_at', 'memory_conversation', ['user_id', 'updated_at'], unique=False)
    op.create_index('uq_memory_conversation_user_conversation_id', 'memory_conversation', ['user_id', 'conversation_id'], unique=True)
    op.create_index('uq_memory_conversation_user_source_session', 'memory_conversation', ['user_id', 'external_source', 'external_session_id'], unique=True)
    op.create_table('memory_index',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='DB row id'),
    sa.Column('memory_id', sa.String(length=120), nullable=False, comment='Stable memory id from file frontmatter or path hash'),
    sa.Column('memory_type', sa.String(length=32), nullable=False, comment='Memory schema name or project index family'),
    sa.Column('memory_level', sa.String(length=8), nullable=False, comment='l0 | l1 | l2'),
    sa.Column('user_id', sa.String(length=100), nullable=False, comment='Owning user id'),
    sa.Column('project_id', sa.String(length=255), nullable=True, comment='Owning project id when applicable'),
    sa.Column('scope_type', sa.String(length=32), nullable=False, comment='user | agent'),
    sa.Column('directory_path', sa.String(length=1024), nullable=False, comment='Parent committed directory path'),
    sa.Column('file_path', sa.String(length=1024), nullable=False, comment='Committed file path'),
    sa.Column('filename', sa.String(length=255), nullable=False, comment='Committed file name'),
    sa.Column('status', sa.String(length=32), nullable=True, comment='active | archived | draft'),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False, comment='Projected tags array'),
    sa.Column('file_sha256', sa.String(length=64), nullable=False, comment='Hash of committed file content'),
    sa.Column('content_bytes', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='Committed file size in bytes'),
    sa.Column('projection_payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False, comment='Projected machine-readable attributes from committed file metadata'),
    sa.Column('memory_created_at', sa.DateTime(timezone=True), nullable=True, comment='Frontmatter created_at from file'),
    sa.Column('memory_updated_at', sa.DateTime(timezone=True), nullable=True, comment='Frontmatter updated_at from file'),
    sa.Column('indexed_at', sa.DateTime(timezone=True), nullable=False, comment='Projection refresh time'),
    sa.Column('refreshed_by_task_id', sa.String(length=64), nullable=True, comment='Last memory_write_task.task_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_path', name='uq_memory_index_file_path'),
    sa.UniqueConstraint('memory_id', name='uq_memory_index_memory_id'),
    comment='Derived metadata index for committed memory and navigation files'
    )
    op.create_index('idx_memory_index_directory_path', 'memory_index', ['directory_path'], unique=False)
    op.create_index('idx_memory_index_memory_updated_at', 'memory_index', ['memory_updated_at'], unique=False)
    op.create_index('idx_memory_index_project_id', 'memory_index', ['project_id'], unique=False)
    op.create_index('idx_memory_index_user_level', 'memory_index', ['user_id', 'memory_level'], unique=False)
    op.create_index('idx_memory_index_user_type', 'memory_index', ['user_id', 'memory_type'], unique=False)
    op.create_table('memory_navigation_index',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='DB row id'),
    sa.Column('memory_id', sa.String(length=120), nullable=False, comment='Stable memory id from file frontmatter or path hash'),
    sa.Column('user_id', sa.String(length=100), nullable=False, comment='Owning user id'),
    sa.Column('project_id', sa.String(length=255), nullable=True, comment='Owning project id when applicable'),
    sa.Column('memory_type', sa.String(length=32), nullable=False, comment='Memory schema name'),
    sa.Column('memory_level', sa.String(length=8), nullable=False, comment='l0 | l1'),
    sa.Column('branch_path', sa.String(length=1024), nullable=False, comment='Committed branch directory path'),
    sa.Column('file_path', sa.String(length=1024), nullable=False, comment='Committed overview.md or summary.md path'),
    sa.Column('vector_doc_id', sa.String(length=120), nullable=False, comment='Milvus document id for this navigation document'),
    sa.Column('abstract_text', sa.Text(), nullable=False, comment='Full overview.md or summary.md body text'),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False, comment='Projected tags array'),
    sa.Column('memory_updated_at', sa.DateTime(timezone=True), nullable=True, comment='Frontmatter updated_at from file'),
    sa.Column('indexed_at', sa.DateTime(timezone=True), nullable=False, comment='Projection refresh time'),
    sa.Column('refreshed_by_task_id', sa.String(length=64), nullable=True, comment='Last memory_write_task.task_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_path', name='uq_memory_navigation_index_file_path'),
    sa.UniqueConstraint('vector_doc_id', name='uq_memory_navigation_index_vector_doc_id'),
    comment='Derived navigation summary metadata for programmer-memory find indexes'
    )
    op.create_index('idx_memory_navigation_index_branch_path', 'memory_navigation_index', ['branch_path'], unique=False)
    op.create_index('idx_memory_navigation_index_memory_updated_at', 'memory_navigation_index', ['memory_updated_at'], unique=False)
    op.create_index('idx_memory_navigation_index_project_id', 'memory_navigation_index', ['project_id'], unique=False)
    op.create_index('idx_memory_navigation_index_user_level', 'memory_navigation_index', ['user_id', 'memory_level'], unique=False)
    op.create_table('memory_retrieval_hint',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='DB row id'),
    sa.Column('memory_id', sa.String(length=120), nullable=False, comment='Stable memory id from file frontmatter'),
    sa.Column('user_id', sa.String(length=100), nullable=False, comment='Owning user id'),
    sa.Column('project_id', sa.String(length=255), nullable=True, comment='Owning project id when applicable'),
    sa.Column('kind', sa.String(length=32), nullable=False, comment='Concrete file kind'),
    sa.Column('file_path', sa.String(length=1024), nullable=False, comment='Committed memory file path'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='Human-readable title'),
    sa.Column('primary_topic', sa.String(length=255), nullable=True, comment='Primary retrieval topic'),
    sa.Column('body_summary', sa.Text(), nullable=True, comment='Short retrieval-safe summary'),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False, comment='Projected tags'),
    sa.Column('aliases', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False, comment='Projected aliases'),
    sa.Column('entity_refs', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False, comment='Projected entity refs'),
    sa.Column('keywords', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False, comment='Projected retrieval keywords'),
    sa.Column('query_hints', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False, comment='Suggested query phrases'),
    sa.Column('importance_score', sa.Numeric(precision=5, scale=4), nullable=True, comment='Optional projector-derived importance score'),
    sa.Column('freshness_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp used for freshness weighting'),
    sa.Column('indexed_at', sa.DateTime(timezone=True), nullable=False, comment='Refresh time'),
    sa.Column('refreshed_by_task_id', sa.String(length=64), nullable=True, comment='Last memory_write_task.task_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('memory_id', name='uq_memory_retrieval_hint_memory_id'),
    comment='Derived retrieval hint metadata projected from committed memories'
    )
    op.create_index('idx_memory_retrieval_hint_file_path', 'memory_retrieval_hint', ['file_path'], unique=False)
    op.create_index('idx_memory_retrieval_hint_kind', 'memory_retrieval_hint', ['kind'], unique=False)
    op.create_index('idx_memory_retrieval_hint_user_topic', 'memory_retrieval_hint', ['user_id', 'primary_topic'], unique=False)
    op.create_table('memory_write_task',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='DB row id'),
    sa.Column('task_id', sa.String(length=64), nullable=False, comment='Public task id'),
    sa.Column('trigger_type', sa.String(length=32), nullable=False, comment='memory_api | session_commit'),
    sa.Column('user_id', sa.String(length=100), nullable=True, comment='Owning user id'),
    sa.Column('agent_id', sa.String(length=100), nullable=True, comment='Owning agent id'),
    sa.Column('project_id', sa.String(length=255), nullable=True, comment='Project id'),
    sa.Column('trace_id', sa.String(length=64), nullable=False, comment='Trace id'),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False, comment='Idempotency key'),
    sa.Column('source_ref', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False, comment='Stable source reference for background extraction'),
    sa.Column('archive_ref', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Archived source details used by worker'),
    sa.Column('status', sa.String(length=32), nullable=True, comment='Terminal task outcome: success | failed'),
    sa.Column('phase', sa.String(length=64), server_default=sa.text("'accepted'"), nullable=False, comment='Current processing phase'),
    sa.Column('failure_message', sa.Text(), nullable=True, comment='Failure message'),
    sa.Column('queued_at', sa.DateTime(), nullable=True, comment='Queue ack timestamp'),
    sa.Column('started_at', sa.DateTime(), nullable=True, comment='Worker started timestamp'),
    sa.Column('completed_at', sa.DateTime(), nullable=True, comment='Terminal completion timestamp'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='Creation time'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='Last update time'),
    sa.PrimaryKeyConstraint('id'),
    comment='Async memory write task lifecycle state'
    )
    op.create_index('idx_memory_write_task_created_at', 'memory_write_task', ['created_at'], unique=False)
    op.create_index('idx_memory_write_task_idempotency', 'memory_write_task', ['idempotency_key'], unique=False)
    op.create_index('idx_memory_write_task_phase', 'memory_write_task', ['phase'], unique=False)
    op.create_index('idx_memory_write_task_status', 'memory_write_task', ['status'], unique=False)
    op.create_index('idx_memory_write_task_task_id', 'memory_write_task', ['task_id'], unique=True)
    op.create_table('auth_role_permission',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='role-permission relation id'),
    sa.Column('role_id', sa.Integer(), nullable=False, comment='role id'),
    sa.Column('permission_id', sa.Integer(), nullable=False, comment='permission id'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='relation create time'),
    sa.ForeignKeyConstraint(['permission_id'], ['auth_permission.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['auth_role.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'permission_id', name='uq_auth_role_permission_role_permission'),
    comment='auth role-permission relation table'
    )
    op.create_index('idx_auth_role_permission_permission_id', 'auth_role_permission', ['permission_id'], unique=False)
    op.create_index('idx_auth_role_permission_role_id', 'auth_role_permission', ['role_id'], unique=False)
    op.create_index(op.f('ix_auth_role_permission_id'), 'auth_role_permission', ['id'], unique=False)
    op.create_table('auth_user_role',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='user-role relation id'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='user id'),
    sa.Column('role_id', sa.Integer(), nullable=False, comment='role id'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='relation create time'),
    sa.ForeignKeyConstraint(['role_id'], ['auth_role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'role_id', name='uq_auth_user_role_user_role'),
    comment='auth user-role relation table'
    )
    op.create_index('idx_auth_user_role_role_id', 'auth_user_role', ['role_id'], unique=False)
    op.create_index('idx_auth_user_role_user_id', 'auth_user_role', ['user_id'], unique=False)
    op.create_index(op.f('ix_auth_user_role_id'), 'auth_user_role', ['id'], unique=False)
    op.drop_index(op.f('idx_event_log_event_type'), table_name='event_logs')
    op.drop_index(op.f('idx_event_log_request_id'), table_name='event_logs')
    op.drop_index(op.f('idx_event_log_session_id'), table_name='event_logs')
    op.drop_index(op.f('idx_event_log_timestamp'), table_name='event_logs')
    op.drop_index(op.f('ix_event_logs_id'), table_name='event_logs')
    op.drop_table('event_logs')
    op.drop_index(op.f('idx_memory_learning_params_user_created'), table_name='memory_learning_params')
    op.drop_table('memory_learning_params')
    op.drop_table('memory_base')
    op.drop_index(op.f('idx_execution_record_plan_id'), table_name='execution_records')
    op.drop_index(op.f('idx_execution_record_session_id'), table_name='execution_records')
    op.drop_index(op.f('idx_execution_record_status'), table_name='execution_records')
    op.drop_index(op.f('idx_execution_record_todo_id'), table_name='execution_records')
    op.drop_index(op.f('ix_execution_records_id'), table_name='execution_records')
    op.drop_table('execution_records')
    op.drop_table('memory_retrieval_log')
    op.drop_table('memory_retrieval_result')
    op.drop_index(op.f('idx_memory_created_at'), table_name='memory_record')
    op.drop_index(op.f('idx_memory_domain'), table_name='memory_record')
    op.drop_index(op.f('idx_memory_topic'), table_name='memory_record')
    op.drop_index(op.f('idx_memory_type'), table_name='memory_record')
    op.drop_table('memory_record')
    op.drop_index(op.f('idx_memory_learning_log_user_created'), table_name='memory_learning_log')
    op.drop_table('memory_learning_log')
    op.add_column('user', sa.Column('user_type', sa.String(), nullable=True, comment='account type: admin or user'))
    op.drop_column('user', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=True, comment='user role: admin or user'))
    op.drop_column('user', 'user_type')
    op.create_table('memory_learning_log',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False, comment='用户ID'),
    sa.Column('quality_scored', sa.INTEGER(), autoincrement=False, nullable=True, comment='本轮打分记忆条数'),
    sa.Column('insights_created', sa.INTEGER(), autoincrement=False, nullable=True, comment='本轮生成洞察数'),
    sa.Column('merges_performed', sa.INTEGER(), autoincrement=False, nullable=True, comment='本轮合并主题数'),
    sa.Column('memories_pruned', sa.INTEGER(), autoincrement=False, nullable=True, comment='本轮剪枝记忆数'),
    sa.Column('elapsed_seconds', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='本轮耗时秒数'),
    sa.Column('error', sa.VARCHAR(length=500), autoincrement=False, nullable=True, comment='错误信息，无错误则 NULL'),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('memory_learning_log_pkey'))
    )
    op.create_index(op.f('idx_memory_learning_log_user_created'), 'memory_learning_log', ['user_id', 'created_at'], unique=False)
    op.create_table('memory_record',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('memory_base_id', sa.UUID(), autoincrement=False, nullable=False, comment='关联的 MemoryBase ID'),
    sa.Column('domain', sa.VARCHAR(length=50), server_default=sa.text("'event'::character varying"), autoincrement=False, nullable=False),
    sa.Column('source', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('kb_doc_id', sa.UUID(), autoincrement=False, nullable=True, comment='关联的知识文档ID'),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('accessed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('access_count', sa.INTEGER(), autoincrement=False, nullable=True, comment='被检索次数，检索时自增'),
    sa.Column('user_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True, comment='代理ID'),
    sa.Column('topic', sa.VARCHAR(), server_default=sa.text("''::character varying"), autoincrement=False, nullable=True),
    sa.Column('quality_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='质量分数 0-1，由学习引擎定期更新'),
    sa.Column('deleted', sa.INTEGER(), autoincrement=False, nullable=True, comment='delete flag'),
    sa.ForeignKeyConstraint(['kb_doc_id'], ['knowledge_document.id'], name=op.f('memory_record_kb_doc_id_fkey')),
    sa.ForeignKeyConstraint(['memory_base_id'], ['memory_base.id'], name=op.f('memory_record_memory_base_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('memory_record_pkey'))
    )
    op.create_index(op.f('idx_memory_type'), 'memory_record', ['type'], unique=False)
    op.create_index(op.f('idx_memory_topic'), 'memory_record', ['topic'], unique=False)
    op.create_index(op.f('idx_memory_domain'), 'memory_record', ['domain'], unique=False)
    op.create_index(op.f('idx_memory_created_at'), 'memory_record', ['created_at'], unique=False)
    op.create_table('memory_retrieval_result',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('log_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('memory_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('hit_count', sa.SMALLINT(), autoincrement=False, nullable=True, comment='被几条子查询命中'),
    sa.Column('rag_score', sa.NUMERIC(precision=5, scale=4), autoincrement=False, nullable=True, comment='LLM 融合前的原始向量 score'),
    sa.Column('from_expansion', sa.BOOLEAN(), autoincrement=False, nullable=True, comment='来自图谱邻居扩展'),
    sa.Column('judge_rank', sa.SMALLINT(), autoincrement=False, nullable=True, comment='LLM judge 排序位，NULL=未入选 judge 输出'),
    sa.Column('final_score', sa.NUMERIC(precision=5, scale=4), autoincrement=False, nullable=True),
    sa.Column('final_rank', sa.SMALLINT(), autoincrement=False, nullable=True, comment='最终结果位置，NULL=未进入最终结果'),
    sa.Column('memory_domain', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('memory_type', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('memory_source', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('access_count_at_query', sa.INTEGER(), autoincrement=False, nullable=True, comment='查询时刻的 access_count 快照'),
    sa.PrimaryKeyConstraint('id', name=op.f('memory_retrieval_result_pkey'))
    )
    op.create_table('memory_retrieval_log',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('agent_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('project_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('retrieve_type', sa.VARCHAR(length=10), autoincrement=False, nullable=False, comment='rag | llm'),
    sa.Column('top_k', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('query_hash', sa.VARCHAR(length=16), autoincrement=False, nullable=False, comment='SHA256(query)[:16]'),
    sa.Column('ms_domain_count', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('ms_topic_count', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('latency_step0_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sub_query_count', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('sub_query_failed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('latency_step1_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sub_query_stats', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='[{query_hash, candidate_count, ...}]'),
    sa.Column('candidate_total_raw', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('candidate_total_unique', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('multi_hit_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('multi_hit_max', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('latency_step2_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('judge_input_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('judge_output_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('judge_selection_rate', sa.NUMERIC(precision=4, scale=3), autoincrement=False, nullable=True),
    sa.Column('judge_failed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('latency_step3_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('final_count', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('final_score_avg', sa.NUMERIC(precision=5, scale=4), autoincrement=False, nullable=True),
    sa.Column('final_score_p50', sa.NUMERIC(precision=5, scale=4), autoincrement=False, nullable=True),
    sa.Column('final_score_p10', sa.NUMERIC(precision=5, scale=4), autoincrement=False, nullable=True),
    sa.Column('domain_dist', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('source_dist', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('type_dist', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('latency_total_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('memory_retrieval_log_pkey'))
    )
    op.create_table('execution_records',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False, comment='Row id'),
    sa.Column('todo_id', sa.INTEGER(), autoincrement=False, nullable=True, comment='Associated AgentTodo id'),
    sa.Column('plan_id', sa.INTEGER(), autoincrement=False, nullable=True, comment='Associated AgentPlan id'),
    sa.Column('session_id', sa.VARCHAR(length=200), autoincrement=False, nullable=True, comment='Session id of the execution'),
    sa.Column('agent_id', sa.INTEGER(), autoincrement=False, nullable=True, comment='Agent that executed the capability'),
    sa.Column('capability_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True, comment='tool | skill | agent | workflow | mcp'),
    sa.Column('capability_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True, comment='Name of the capability used'),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False, comment='success | partial | failed'),
    sa.Column('input_payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='Input sent to the capability'),
    sa.Column('output_payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='Output returned by the capability'),
    sa.Column('observation', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='Structured observation: evidence[] and artifacts[]'),
    sa.Column('success_criteria_check', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='Success criteria evaluation results'),
    sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True, comment='Execution start time'),
    sa.Column('ended_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True, comment='Execution end time'),
    sa.Column('latency_ms', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Execution latency in milliseconds'),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False, comment='Record creation time'),
    sa.PrimaryKeyConstraint('id', name=op.f('execution_records_pkey')),
    comment='Logs each todo execution attempt for observability and reflection'
    )
    op.create_index(op.f('ix_execution_records_id'), 'execution_records', ['id'], unique=False)
    op.create_index(op.f('idx_execution_record_todo_id'), 'execution_records', ['todo_id'], unique=False)
    op.create_index(op.f('idx_execution_record_status'), 'execution_records', ['status'], unique=False)
    op.create_index(op.f('idx_execution_record_session_id'), 'execution_records', ['session_id'], unique=False)
    op.create_index(op.f('idx_execution_record_plan_id'), 'execution_records', ['plan_id'], unique=False)
    op.create_table('memory_base',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True, comment='用户ID'),
    sa.Column('domain', sa.VARCHAR(length=50), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False, comment='记忆领域'),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('mem_kb_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True, comment='关联的知识库ID'),
    sa.Column('type', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('deleted', sa.INTEGER(), autoincrement=False, nullable=True, comment='delete flag'),
    sa.PrimaryKeyConstraint('id', name=op.f('memory_base_pkey'))
    )
    op.create_table('memory_learning_params',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False, comment='用户ID'),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False, comment='各组件参数，结构见 ParamOptimizer.DEFAULT_PARAMS'),
    sa.Column('reasoning', sa.TEXT(), autoincrement=False, nullable=True, comment='LLM 给出的调参理由'),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('memory_learning_params_pkey'))
    )
    op.create_index(op.f('idx_memory_learning_params_user_created'), 'memory_learning_params', ['user_id', 'created_at'], unique=False)
    op.create_table('event_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False, comment='Row id'),
    sa.Column('event_id', sa.UUID(), autoincrement=False, nullable=False, comment='Globally unique event identifier (UUID v4)'),
    sa.Column('session_id', sa.VARCHAR(length=200), autoincrement=False, nullable=True, comment='Session associated with the event'),
    sa.Column('request_id', sa.VARCHAR(length=200), autoincrement=False, nullable=True, comment='Request/execution ID associated with the event'),
    sa.Column('event_type', sa.VARCHAR(length=60), autoincrement=False, nullable=False, comment='request_received | intent_analyzed | context_built | capability_selected | plan_created | plan_criticized | todo_created | todo_started | todo_completed | todo_failed | retry_triggered | replan_triggered | response_composed | memory_written'),
    sa.Column('actor', sa.VARCHAR(length=200), autoincrement=False, nullable=True, comment='Agent or component that emitted the event'),
    sa.Column('target_id', sa.VARCHAR(length=200), autoincrement=False, nullable=True, comment='ID of the entity affected (todo_id, plan_id, etc.)'),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='Arbitrary structured data for this event'),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False, comment='Wall-clock time when the event occurred'),
    sa.PrimaryKeyConstraint('id', name=op.f('event_logs_pkey')),
    sa.UniqueConstraint('event_id', name=op.f('event_logs_event_id_key')),
    comment='Append-only audit trail of all orchestration events'
    )
    op.create_index(op.f('ix_event_logs_id'), 'event_logs', ['id'], unique=False)
    op.create_index(op.f('idx_event_log_timestamp'), 'event_logs', ['timestamp'], unique=False)
    op.create_index(op.f('idx_event_log_session_id'), 'event_logs', ['session_id'], unique=False)
    op.create_index(op.f('idx_event_log_request_id'), 'event_logs', ['request_id'], unique=False)
    op.create_index(op.f('idx_event_log_event_type'), 'event_logs', ['event_type'], unique=False)
    op.drop_index(op.f('ix_auth_user_role_id'), table_name='auth_user_role')
    op.drop_index('idx_auth_user_role_user_id', table_name='auth_user_role')
    op.drop_index('idx_auth_user_role_role_id', table_name='auth_user_role')
    op.drop_table('auth_user_role')
    op.drop_index(op.f('ix_auth_role_permission_id'), table_name='auth_role_permission')
    op.drop_index('idx_auth_role_permission_role_id', table_name='auth_role_permission')
    op.drop_index('idx_auth_role_permission_permission_id', table_name='auth_role_permission')
    op.drop_table('auth_role_permission')
    op.drop_index('idx_memory_write_task_task_id', table_name='memory_write_task')
    op.drop_index('idx_memory_write_task_status', table_name='memory_write_task')
    op.drop_index('idx_memory_write_task_phase', table_name='memory_write_task')
    op.drop_index('idx_memory_write_task_idempotency', table_name='memory_write_task')
    op.drop_index('idx_memory_write_task_created_at', table_name='memory_write_task')
    op.drop_table('memory_write_task')
    op.drop_index('idx_memory_retrieval_hint_user_topic', table_name='memory_retrieval_hint')
    op.drop_index('idx_memory_retrieval_hint_kind', table_name='memory_retrieval_hint')
    op.drop_index('idx_memory_retrieval_hint_file_path', table_name='memory_retrieval_hint')
    op.drop_table('memory_retrieval_hint')
    op.drop_index('idx_memory_navigation_index_user_level', table_name='memory_navigation_index')
    op.drop_index('idx_memory_navigation_index_project_id', table_name='memory_navigation_index')
    op.drop_index('idx_memory_navigation_index_memory_updated_at', table_name='memory_navigation_index')
    op.drop_index('idx_memory_navigation_index_branch_path', table_name='memory_navigation_index')
    op.drop_table('memory_navigation_index')
    op.drop_index('idx_memory_index_user_type', table_name='memory_index')
    op.drop_index('idx_memory_index_user_level', table_name='memory_index')
    op.drop_index('idx_memory_index_project_id', table_name='memory_index')
    op.drop_index('idx_memory_index_memory_updated_at', table_name='memory_index')
    op.drop_index('idx_memory_index_directory_path', table_name='memory_index')
    op.drop_table('memory_index')
    op.drop_index('uq_memory_conversation_user_source_session', table_name='memory_conversation')
    op.drop_index('uq_memory_conversation_user_conversation_id', table_name='memory_conversation')
    op.drop_index('idx_memory_conversation_user_updated_at', table_name='memory_conversation')
    op.drop_index('idx_memory_conversation_status', table_name='memory_conversation')
    op.drop_index('idx_memory_conversation_project_updated_at', table_name='memory_conversation')
    op.drop_index('idx_memory_conversation_last_message_at', table_name='memory_conversation')
    op.drop_table('memory_conversation')
    op.drop_index(op.f('ix_auth_role_id'), table_name='auth_role')
    op.drop_index(op.f('ix_auth_role_code'), table_name='auth_role')
    op.drop_table('auth_role')
    op.drop_index('ix_auth_refresh_session_user_status', table_name='auth_refresh_session')
    op.drop_index(op.f('ix_auth_refresh_session_user_id'), table_name='auth_refresh_session')
    op.drop_index(op.f('ix_auth_refresh_session_token_jti'), table_name='auth_refresh_session')
    op.drop_index(op.f('ix_auth_refresh_session_id'), table_name='auth_refresh_session')
    op.drop_table('auth_refresh_session')
    op.drop_index(op.f('ix_auth_permission_id'), table_name='auth_permission')
    op.drop_index(op.f('ix_auth_permission_code'), table_name='auth_permission')
    op.drop_table('auth_permission')
    op.drop_index(op.f('ix_auth_audit_log_id'), table_name='auth_audit_log')
    op.drop_index('idx_auth_audit_log_user_id', table_name='auth_audit_log')
    op.drop_index('idx_auth_audit_log_event', table_name='auth_audit_log')
    op.drop_index('idx_auth_audit_log_created_at', table_name='auth_audit_log')
    op.drop_table('auth_audit_log')
    # ### end Alembic commands ###
