"""Memory system environment variable settings mixin."""

from pydantic_settings import BaseSettings


class MemorySettingsConfig(BaseSettings):
    """Memory-related environment variables — simplified."""

    MEMORY_GATE_DUPLICATE_SIMILARITY: float = 0.95
    MEMORY_TREE_ROOT_DIR: str = "memory_pipeline"
    MEMORY_TREE_LIST_MAX_RESULTS: int = 200
    MEMORY_TREE_READ_MAX_CHARS: int = 200_000
    MEMORY_TREE_SEARCH_MAX_RESULTS: int = 20
    MEMORY_TREE_MAX_FILES: int = 50
    MEMORY_TREE_MAX_CHARS_PER_FILE: int = 4_000
    MEMORY_TREE_MAX_TOTAL_CHARS: int = 20_000
    MEMORY_RETRIEVE_REACT_ENABLED: bool = True
    MEMORY_RETRIEVE_REACT_MAX_STEPS: int = 5
    MEMORY_RETRIEVE_REACT_MAX_SEARCH_ACTIONS: int = 3
    MEMORY_RETRIEVE_REACT_MAX_EXPAND_ACTIONS: int = 2
    MEMORY_RETRIEVE_REACT_CANDIDATE_POOL_MULTIPLIER: int = 4
    MEMORY_RETRIEVE_REACT_JUDGE_POOL_MULTIPLIER: int = 6
    MEMORY_RETRIEVE_REACT_STOP_SCORE: float = 0.88
    MEMORY_RETRIEVE_REACT_MIN_NEW_CANDIDATES: int = 1
    MEMORY_FIND_TOP_K_DEFAULT: int = 10
    MEMORY_FIND_TOP_K_MAX: int = 50
    MEMORY_FIND_SCORE_THRESHOLD_DEFAULT: float = 0.35
    MEMORY_FIND_L0_INITIAL_TOP_K: int = 20
    MEMORY_FIND_L0_MIN_SCORE: float = 0.20
    MEMORY_FIND_L0_EXPAND_TO_L1_THRESHOLD: float = 0.72
    MEMORY_FIND_RERANK_TOP_N: int = 20
    MEMORY_FIND_VECTOR_COLLECTION_PREFIX: str = "memory_find_navigation"
    MEMORY_SEARCH_TOP_K_DEFAULT: int = 10
    MEMORY_SEARCH_TOP_K_MAX: int = 50
    MEMORY_SEARCH_SCORE_THRESHOLD_DEFAULT: float = 0.35
    MEMORY_SEARCH_L0L1_INITIAL_TOP_K: int = 20
    MEMORY_SEARCH_L0L1_MIN_SCORE: float = 0.20
    MEMORY_SEARCH_MAX_SESSION_MESSAGES: int = 12
    MEMORY_SEARCH_MAX_SESSION_CHARS: int = 12000
    MEMORY_SEARCH_QUERY_MAX_CHARS: int = 512
    MEMORY_SEARCH_INCLUDE_TYPES_MAX: int = 20
    MEMORY_SEARCH_CONTENT_PARTS_MAX: int = 8
    MEMORY_SEARCH_TEXT_PART_MAX_CHARS: int = 4000
    MEMORY_SEARCH_MAX_L2_BRANCHES: int = 5
    MEMORY_SEARCH_MAX_L2_FILES_PER_BRANCH: int = 3
    MEMORY_SEARCH_RERANK_TOP_N: int = 20
    MEMORY_SEARCH_L2_READ_MAX_CHARS: int = 12000
